// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package restic

import (
	"context"

	"github.com/pablovarela/media-server-engine/internal/process"
	mock "github.com/stretchr/testify/mock"
)

// newMockRunner creates a new instance of mockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRunner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockRunner is an autogenerated mock type for the Runner type
type mockRunner struct {
	mock.Mock
}

type mockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRunner) EXPECT() *mockRunner_Expecter {
	return &mockRunner_Expecter{mock: &_m.Mock}
}

// Output provides a mock function for the type mockRunner
func (_mock *mockRunner) Output(ctx context.Context, c process.Command) (process.Result, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 process.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, process.Command) (process.Result, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, process.Command) process.Result); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Get(0).(process.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, process.Command) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockRunner_Output_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Output'
type mockRunner_Output_Call struct {
	*mock.Call
}

// Output is a helper method to define mock.On call
//   - ctx context.Context
//   - c process.Command
func (_e *mockRunner_Expecter) Output(ctx any, c any) *mockRunner_Output_Call {
	return &mockRunner_Output_Call{Call: _e.mock.On("Output", ctx, c)}
}

func (_c *mockRunner_Output_Call) Run(run func(ctx context.Context, c process.Command)) *mockRunner_Output_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 process.Command
		if args[1] != nil {
			arg1 = args[1].(process.Command)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockRunner_Output_Call) Return(result process.Result, err error) *mockRunner_Output_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockRunner_Output_Call) RunAndReturn(run func(ctx context.Context, c process.Command) (process.Result, error)) *mockRunner_Output_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type mockRunner
func (_mock *mockRunner) Run(ctx context.Context, c process.Command) (int, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, process.Command) (int, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, process.Command) int); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, process.Command) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - c process.Command
func (_e *mockRunner_Expecter) Run(ctx any, c any) *mockRunner_Run_Call {
	return &mockRunner_Run_Call{Call: _e.mock.On("Run", ctx, c)}
}

func (_c *mockRunner_Run_Call) Run(run func(ctx context.Context, c process.Command)) *mockRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 process.Command
		if args[1] != nil {
			arg1 = args[1].(process.Command)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockRunner_Run_Call) Return(n int, err error) *mockRunner_Run_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockRunner_Run_Call) RunAndReturn(run func(ctx context.Context, c process.Command) (int, error)) *mockRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
