// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package configure

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockRestorer creates a new instance of mockRestorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRestorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRestorer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockRestorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockRestorer is an autogenerated mock type for the restorer type
type mockRestorer struct {
	mock.Mock
}

type mockRestorer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRestorer) EXPECT() *mockRestorer_Expecter {
	return &mockRestorer_Expecter{mock: &_m.Mock}
}

// Restore provides a mock function for the type mockRestorer
func (_mock *mockRestorer) Restore(ctx context.Context, paths []string) error {
	ret := _mock.Called(ctx, paths)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, paths)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockRestorer_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type mockRestorer_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - paths []string
func (_e *mockRestorer_Expecter) Restore(ctx any, paths any) *mockRestorer_Restore_Call {
	return &mockRestorer_Restore_Call{Call: _e.mock.On("Restore", ctx, paths)}
}

func (_c *mockRestorer_Restore_Call) Run(run func(ctx context.Context, paths []string)) *mockRestorer_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockRestorer_Restore_Call) Return(err error) *mockRestorer_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockRestorer_Restore_Call) RunAndReturn(run func(ctx context.Context, paths []string) error) *mockRestorer_Restore_Call {
	_c.Call.Return(run)
	return _c
}
