// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package configure

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockPrompter creates a new instance of mockPrompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPrompter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockPrompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockPrompter is an autogenerated mock type for the Prompter type
type mockPrompter struct {
	mock.Mock
}

type mockPrompter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPrompter) EXPECT() *mockPrompter_Expecter {
	return &mockPrompter_Expecter{mock: &_m.Mock}
}

// Confirm provides a mock function for the type mockPrompter
func (_mock *mockPrompter) Confirm(question string, lines []string) (bool, error) {
	ret := _mock.Called(question, lines)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []string) (bool, error)); ok {
		return returnFunc(question, lines)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string) bool); ok {
		r0 = returnFunc(question, lines)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = returnFunc(question, lines)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPrompter_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type mockPrompter_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - question string
//   - lines []string
func (_e *mockPrompter_Expecter) Confirm(question any, lines any) *mockPrompter_Confirm_Call {
	return &mockPrompter_Confirm_Call{Call: _e.mock.On("Confirm", question, lines)}
}

func (_c *mockPrompter_Confirm_Call) Run(run func(question string, lines []string)) *mockPrompter_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPrompter_Confirm_Call) Return(b bool, err error) *mockPrompter_Confirm_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockPrompter_Confirm_Call) RunAndReturn(run func(question string, lines []string) (bool, error)) *mockPrompter_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// Menu provides a mock function for the type mockPrompter
func (_mock *mockPrompter) Menu(title string, items []MenuItem) (string, error) {
	ret := _mock.Called(title, items)

	if len(ret) == 0 {
		panic("no return value specified for Menu")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []MenuItem) (string, error)); ok {
		return returnFunc(title, items)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []MenuItem) string); ok {
		r0 = returnFunc(title, items)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []MenuItem) error); ok {
		r1 = returnFunc(title, items)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPrompter_Menu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Menu'
type mockPrompter_Menu_Call struct {
	*mock.Call
}

// Menu is a helper method to define mock.On call
//   - title string
//   - items []MenuItem
func (_e *mockPrompter_Expecter) Menu(title any, items any) *mockPrompter_Menu_Call {
	return &mockPrompter_Menu_Call{Call: _e.mock.On("Menu", title, items)}
}

func (_c *mockPrompter_Menu_Call) Run(run func(title string, items []MenuItem)) *mockPrompter_Menu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []MenuItem
		if args[1] != nil {
			arg1 = args[1].([]MenuItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPrompter_Menu_Call) Return(s string, err error) *mockPrompter_Menu_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockPrompter_Menu_Call) RunAndReturn(run func(title string, items []MenuItem) (string, error)) *mockPrompter_Menu_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function for the type mockPrompter
func (_mock *mockPrompter) Rotate(apps []App) ([]App, error) {
	ret := _mock.Called(apps)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 []App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]App) ([]App, error)); ok {
		return returnFunc(apps)
	}
	if returnFunc, ok := ret.Get(0).(func([]App) []App); ok {
		r0 = returnFunc(apps)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]App) error); ok {
		r1 = returnFunc(apps)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPrompter_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type mockPrompter_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - apps []App
func (_e *mockPrompter_Expecter) Rotate(apps any) *mockPrompter_Rotate_Call {
	return &mockPrompter_Rotate_Call{Call: _e.mock.On("Rotate", apps)}
}

func (_c *mockPrompter_Rotate_Call) Run(run func(apps []App)) *mockPrompter_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []App
		if args[0] != nil {
			arg0 = args[0].([]App)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockPrompter_Rotate_Call) Return(apps1 []App, err error) *mockPrompter_Rotate_Call {
	_c.Call.Return(apps1, err)
	return _c
}

func (_c *mockPrompter_Rotate_Call) RunAndReturn(run func(apps []App) ([]App, error)) *mockPrompter_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// Section provides a mock function for the type mockPrompter
func (_mock *mockPrompter) Section(title string, fields []Field, current map[string]string, problem string) (map[string]string, error) {
	ret := _mock.Called(title, fields, current, problem)

	if len(ret) == 0 {
		panic("no return value specified for Section")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []Field, map[string]string, string) (map[string]string, error)); ok {
		return returnFunc(title, fields, current, problem)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []Field, map[string]string, string) map[string]string); ok {
		r0 = returnFunc(title, fields, current, problem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []Field, map[string]string, string) error); ok {
		r1 = returnFunc(title, fields, current, problem)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPrompter_Section_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Section'
type mockPrompter_Section_Call struct {
	*mock.Call
}

// Section is a helper method to define mock.On call
//   - title string
//   - fields []Field
//   - current map[string]string
//   - problem string
func (_e *mockPrompter_Expecter) Section(title any, fields any, current any, problem any) *mockPrompter_Section_Call {
	return &mockPrompter_Section_Call{Call: _e.mock.On("Section", title, fields, current, problem)}
}

func (_c *mockPrompter_Section_Call) Run(run func(title string, fields []Field, current map[string]string, problem string)) *mockPrompter_Section_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []Field
		if args[1] != nil {
			arg1 = args[1].([]Field)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockPrompter_Section_Call) Return(stringToString map[string]string, err error) *mockPrompter_Section_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *mockPrompter_Section_Call) RunAndReturn(run func(title string, fields []Field, current map[string]string, problem string) (map[string]string, error)) *mockPrompter_Section_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRestorer creates a new instance of mockRestorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRestorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRestorer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockRestorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockRestorer is an autogenerated mock type for the restorer type
type mockRestorer struct {
	mock.Mock
}

type mockRestorer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRestorer) EXPECT() *mockRestorer_Expecter {
	return &mockRestorer_Expecter{mock: &_m.Mock}
}

// Restore provides a mock function for the type mockRestorer
func (_mock *mockRestorer) Restore(ctx context.Context, paths []string) error {
	ret := _mock.Called(ctx, paths)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, paths)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockRestorer_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type mockRestorer_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - paths []string
func (_e *mockRestorer_Expecter) Restore(ctx any, paths any) *mockRestorer_Restore_Call {
	return &mockRestorer_Restore_Call{Call: _e.mock.On("Restore", ctx, paths)}
}

func (_c *mockRestorer_Restore_Call) Run(run func(ctx context.Context, paths []string)) *mockRestorer_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockRestorer_Restore_Call) Return(err error) *mockRestorer_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockRestorer_Restore_Call) RunAndReturn(run func(ctx context.Context, paths []string) error) *mockRestorer_Restore_Call {
	_c.Call.Return(run)
	return _c
}
