// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apply

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockStack creates a new instance of mockStack. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStack(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStack {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockStack{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockStack is an autogenerated mock type for the Stack type
type mockStack struct {
	mock.Mock
}

type mockStack_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStack) EXPECT() *mockStack_Expecter {
	return &mockStack_Expecter{mock: &_m.Mock}
}

// BindSources provides a mock function for the type mockStack
func (_mock *mockStack) BindSources() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BindSources")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// mockStack_BindSources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindSources'
type mockStack_BindSources_Call struct {
	*mock.Call
}

// BindSources is a helper method to define mock.On call
func (_e *mockStack_Expecter) BindSources() *mockStack_BindSources_Call {
	return &mockStack_BindSources_Call{Call: _e.mock.On("BindSources")}
}

func (_c *mockStack_BindSources_Call) Run(run func()) *mockStack_BindSources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockStack_BindSources_Call) Return(strings []string) *mockStack_BindSources_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *mockStack_BindSources_Call) RunAndReturn(run func() []string) *mockStack_BindSources_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function for the type mockStack
func (_mock *mockStack) Pull(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockStack_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type mockStack_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockStack_Expecter) Pull(ctx any) *mockStack_Pull_Call {
	return &mockStack_Pull_Call{Call: _e.mock.On("Pull", ctx)}
}

func (_c *mockStack_Pull_Call) Run(run func(ctx context.Context)) *mockStack_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockStack_Pull_Call) Return(s string, err error) *mockStack_Pull_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockStack_Pull_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *mockStack_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Reattach provides a mock function for the type mockStack
func (_mock *mockStack) Reattach(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Reattach")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockStack_Reattach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reattach'
type mockStack_Reattach_Call struct {
	*mock.Call
}

// Reattach is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockStack_Expecter) Reattach(ctx any) *mockStack_Reattach_Call {
	return &mockStack_Reattach_Call{Call: _e.mock.On("Reattach", ctx)}
}

func (_c *mockStack_Reattach_Call) Run(run func(ctx context.Context)) *mockStack_Reattach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockStack_Reattach_Call) Return(s string, err error) *mockStack_Reattach_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockStack_Reattach_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *mockStack_Reattach_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type mockStack
func (_mock *mockStack) Up(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockStack_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type mockStack_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockStack_Expecter) Up(ctx any) *mockStack_Up_Call {
	return &mockStack_Up_Call{Call: _e.mock.On("Up", ctx)}
}

func (_c *mockStack_Up_Call) Run(run func(ctx context.Context)) *mockStack_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockStack_Up_Call) Return(s string, err error) *mockStack_Up_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockStack_Up_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *mockStack_Up_Call {
	_c.Call.Return(run)
	return _c
}

// newMockChecks creates a new instance of mockChecks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockChecks(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockChecks {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockChecks{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockChecks is an autogenerated mock type for the Checks type
type mockChecks struct {
	mock.Mock
}

type mockChecks_Expecter struct {
	mock *mock.Mock
}

func (_m *mockChecks) EXPECT() *mockChecks_Expecter {
	return &mockChecks_Expecter{mock: &_m.Mock}
}

// SetUp provides a mock function for the type mockChecks
func (_mock *mockChecks) SetUp(ctx context.Context) ([]string, []string) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SetUp")
	}

	var r0 []string
	var r1 []string
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, []string)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) []string); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	return r0, r1
}

// mockChecks_SetUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUp'
type mockChecks_SetUp_Call struct {
	*mock.Call
}

// SetUp is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockChecks_Expecter) SetUp(ctx any) *mockChecks_SetUp_Call {
	return &mockChecks_SetUp_Call{Call: _e.mock.On("SetUp", ctx)}
}

func (_c *mockChecks_SetUp_Call) Run(run func(ctx context.Context)) *mockChecks_SetUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockChecks_SetUp_Call) Return(set []string, failures []string) *mockChecks_SetUp_Call {
	_c.Call.Return(set, failures)
	return _c
}

func (_c *mockChecks_SetUp_Call) RunAndReturn(run func(ctx context.Context) ([]string, []string)) *mockChecks_SetUp_Call {
	_c.Call.Return(run)
	return _c
}

// newMockWiring creates a new instance of mockWiring. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockWiring(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockWiring {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockWiring{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockWiring is an autogenerated mock type for the Wiring type
type mockWiring struct {
	mock.Mock
}

type mockWiring_Expecter struct {
	mock *mock.Mock
}

func (_m *mockWiring) EXPECT() *mockWiring_Expecter {
	return &mockWiring_Expecter{mock: &_m.Mock}
}

// Wire provides a mock function for the type mockWiring
func (_mock *mockWiring) Wire(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Wire")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockWiring_Wire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wire'
type mockWiring_Wire_Call struct {
	*mock.Call
}

// Wire is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockWiring_Expecter) Wire(ctx any) *mockWiring_Wire_Call {
	return &mockWiring_Wire_Call{Call: _e.mock.On("Wire", ctx)}
}

func (_c *mockWiring_Wire_Call) Run(run func(ctx context.Context)) *mockWiring_Wire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockWiring_Wire_Call) Return(s string, err error) *mockWiring_Wire_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockWiring_Wire_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *mockWiring_Wire_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPage creates a new instance of mockPage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPage(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPage {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockPage{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockPage is an autogenerated mock type for the Page type
type mockPage struct {
	mock.Mock
}

type mockPage_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPage) EXPECT() *mockPage_Expecter {
	return &mockPage_Expecter{mock: &_m.Mock}
}

// Reload provides a mock function for the type mockPage
func (_mock *mockPage) Reload(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Reload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPage_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type mockPage_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockPage_Expecter) Reload(ctx any) *mockPage_Reload_Call {
	return &mockPage_Reload_Call{Call: _e.mock.On("Reload", ctx)}
}

func (_c *mockPage_Reload_Call) Run(run func(ctx context.Context)) *mockPage_Reload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockPage_Reload_Call) Return(err error) *mockPage_Reload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPage_Reload_Call) RunAndReturn(run func(ctx context.Context) error) *mockPage_Reload_Call {
	_c.Call.Return(run)
	return _c
}

// newMockImages creates a new instance of mockImages. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockImages(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockImages {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockImages{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockImages is an autogenerated mock type for the Images type
type mockImages struct {
	mock.Mock
}

type mockImages_Expecter struct {
	mock *mock.Mock
}

func (_m *mockImages) EXPECT() *mockImages_Expecter {
	return &mockImages_Expecter{mock: &_m.Mock}
}

// Prune provides a mock function for the type mockImages
func (_mock *mockImages) Prune(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockImages_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type mockImages_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockImages_Expecter) Prune(ctx any) *mockImages_Prune_Call {
	return &mockImages_Prune_Call{Call: _e.mock.On("Prune", ctx)}
}

func (_c *mockImages_Prune_Call) Run(run func(ctx context.Context)) *mockImages_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockImages_Prune_Call) Return(err error) *mockImages_Prune_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockImages_Prune_Call) RunAndReturn(run func(ctx context.Context) error) *mockImages_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// newMockTimers creates a new instance of mockTimers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTimers(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTimers {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockTimers{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockTimers is an autogenerated mock type for the Timers type
type mockTimers struct {
	mock.Mock
}

type mockTimers_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTimers) EXPECT() *mockTimers_Expecter {
	return &mockTimers_Expecter{mock: &_m.Mock}
}

// Set provides a mock function for the type mockTimers
func (_mock *mockTimers) Set(ctx context.Context) (string, []string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 string
	var r1 []string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, []string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) []string); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockTimers_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type mockTimers_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockTimers_Expecter) Set(ctx any) *mockTimers_Set_Call {
	return &mockTimers_Set_Call{Call: _e.mock.On("Set", ctx)}
}

func (_c *mockTimers_Set_Call) Run(run func(ctx context.Context)) *mockTimers_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockTimers_Set_Call) Return(result string, warnings []string, err error) *mockTimers_Set_Call {
	_c.Call.Return(result, warnings, err)
	return _c
}

func (_c *mockTimers_Set_Call) RunAndReturn(run func(ctx context.Context) (string, []string, error)) *mockTimers_Set_Call {
	_c.Call.Return(run)
	return _c
}
