all: true
template: testify
dir: "{{.InterfaceDir}}"
filename: mocks_test.go
pkgname: "{{.SrcPackageName}}"
structname: "mock{{.InterfaceName | firstUpper}}"
packages:
  github.com/pablovarela/media-server-engine/internal/selfupdate: {}
  github.com/pablovarela/media-server-engine/cmd: {}
  github.com/pablovarela/media-server-engine/internal/compose: {}
  github.com/pablovarela/media-server-engine/internal/images: {}
  github.com/pablovarela/media-server-engine/internal/restic: {}
  github.com/pablovarela/media-server-engine/internal/backup: {}
  github.com/pablovarela/media-server-engine/internal/gitconfig: {}
  github.com/pablovarela/media-server-engine/internal/apply: {}
