// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package create

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockSteps creates a new instance of mockSteps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSteps(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSteps {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockSteps{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockSteps is an autogenerated mock type for the Steps type
type mockSteps struct {
	mock.Mock
}

type mockSteps_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSteps) EXPECT() *mockSteps_Expecter {
	return &mockSteps_Expecter{mock: &_m.Mock}
}

// AddKey provides a mock function for the type mockSteps
func (_mock *mockSteps) AddKey(ctx context.Context) (Undo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AddKey")
	}

	var r0 Undo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (Undo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) Undo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Undo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockSteps_AddKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddKey'
type mockSteps_AddKey_Call struct {
	*mock.Call
}

// AddKey is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSteps_Expecter) AddKey(ctx any) *mockSteps_AddKey_Call {
	return &mockSteps_AddKey_Call{Call: _e.mock.On("AddKey", ctx)}
}

func (_c *mockSteps_AddKey_Call) Run(run func(ctx context.Context)) *mockSteps_AddKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockSteps_AddKey_Call) Return(undo Undo, err error) *mockSteps_AddKey_Call {
	_c.Call.Return(undo, err)
	return _c
}

func (_c *mockSteps_AddKey_Call) RunAndReturn(run func(ctx context.Context) (Undo, error)) *mockSteps_AddKey_Call {
	_c.Call.Return(run)
	return _c
}

// Apply provides a mock function for the type mockSteps
func (_mock *mockSteps) Apply(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockSteps_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type mockSteps_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSteps_Expecter) Apply(ctx any) *mockSteps_Apply_Call {
	return &mockSteps_Apply_Call{Call: _e.mock.On("Apply", ctx)}
}

func (_c *mockSteps_Apply_Call) Run(run func(ctx context.Context)) *mockSteps_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockSteps_Apply_Call) Return(err error) *mockSteps_Apply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockSteps_Apply_Call) RunAndReturn(run func(ctx context.Context) error) *mockSteps_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// CheckMachine provides a mock function for the type mockSteps
func (_mock *mockSteps) CheckMachine(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckMachine")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockSteps_CheckMachine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckMachine'
type mockSteps_CheckMachine_Call struct {
	*mock.Call
}

// CheckMachine is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSteps_Expecter) CheckMachine(ctx any) *mockSteps_CheckMachine_Call {
	return &mockSteps_CheckMachine_Call{Call: _e.mock.On("CheckMachine", ctx)}
}

func (_c *mockSteps_CheckMachine_Call) Run(run func(ctx context.Context)) *mockSteps_CheckMachine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockSteps_CheckMachine_Call) Return(err error) *mockSteps_CheckMachine_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockSteps_CheckMachine_Call) RunAndReturn(run func(ctx context.Context) error) *mockSteps_CheckMachine_Call {
	_c.Call.Return(run)
	return _c
}

// CheckName provides a mock function for the type mockSteps
func (_mock *mockSteps) CheckName(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockSteps_CheckName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckName'
type mockSteps_CheckName_Call struct {
	*mock.Call
}

// CheckName is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSteps_Expecter) CheckName(ctx any) *mockSteps_CheckName_Call {
	return &mockSteps_CheckName_Call{Call: _e.mock.On("CheckName", ctx)}
}

func (_c *mockSteps_CheckName_Call) Run(run func(ctx context.Context)) *mockSteps_CheckName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockSteps_CheckName_Call) Return(err error) *mockSteps_CheckName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockSteps_CheckName_Call) RunAndReturn(run func(ctx context.Context) error) *mockSteps_CheckName_Call {
	_c.Call.Return(run)
	return _c
}

// ClaimMain provides a mock function for the type mockSteps
func (_mock *mockSteps) ClaimMain(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClaimMain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockSteps_ClaimMain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimMain'
type mockSteps_ClaimMain_Call struct {
	*mock.Call
}

// ClaimMain is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSteps_Expecter) ClaimMain(ctx any) *mockSteps_ClaimMain_Call {
	return &mockSteps_ClaimMain_Call{Call: _e.mock.On("ClaimMain", ctx)}
}

func (_c *mockSteps_ClaimMain_Call) Run(run func(ctx context.Context)) *mockSteps_ClaimMain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockSteps_ClaimMain_Call) Return(err error) *mockSteps_ClaimMain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockSteps_ClaimMain_Call) RunAndReturn(run func(ctx context.Context) error) *mockSteps_ClaimMain_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type mockSteps
func (_mock *mockSteps) Commit(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockSteps_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type mockSteps_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSteps_Expecter) Commit(ctx any) *mockSteps_Commit_Call {
	return &mockSteps_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *mockSteps_Commit_Call) Run(run func(ctx context.Context)) *mockSteps_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockSteps_Commit_Call) Return(err error) *mockSteps_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockSteps_Commit_Call) RunAndReturn(run func(ctx context.Context) error) *mockSteps_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Configure provides a mock function for the type mockSteps
func (_mock *mockSteps) Configure(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockSteps_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type mockSteps_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSteps_Expecter) Configure(ctx any) *mockSteps_Configure_Call {
	return &mockSteps_Configure_Call{Call: _e.mock.On("Configure", ctx)}
}

func (_c *mockSteps_Configure_Call) Run(run func(ctx context.Context)) *mockSteps_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockSteps_Configure_Call) Return(err error) *mockSteps_Configure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockSteps_Configure_Call) RunAndReturn(run func(ctx context.Context) error) *mockSteps_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type mockSteps
func (_mock *mockSteps) Publish(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockSteps_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type mockSteps_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSteps_Expecter) Publish(ctx any) *mockSteps_Publish_Call {
	return &mockSteps_Publish_Call{Call: _e.mock.On("Publish", ctx)}
}

func (_c *mockSteps_Publish_Call) Run(run func(ctx context.Context)) *mockSteps_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockSteps_Publish_Call) Return(created bool, err error) *mockSteps_Publish_Call {
	_c.Call.Return(created, err)
	return _c
}

func (_c *mockSteps_Publish_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *mockSteps_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Summary provides a mock function for the type mockSteps
func (_mock *mockSteps) Summary(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Summary")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockSteps_Summary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Summary'
type mockSteps_Summary_Call struct {
	*mock.Call
}

// Summary is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSteps_Expecter) Summary(ctx any) *mockSteps_Summary_Call {
	return &mockSteps_Summary_Call{Call: _e.mock.On("Summary", ctx)}
}

func (_c *mockSteps_Summary_Call) Run(run func(ctx context.Context)) *mockSteps_Summary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockSteps_Summary_Call) Return(s string) *mockSteps_Summary_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockSteps_Summary_Call) RunAndReturn(run func(ctx context.Context) string) *mockSteps_Summary_Call {
	_c.Call.Return(run)
	return _c
}

// WriteConfig provides a mock function for the type mockSteps
func (_mock *mockSteps) WriteConfig(ctx context.Context) (Undo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WriteConfig")
	}

	var r0 Undo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (Undo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) Undo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Undo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockSteps_WriteConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteConfig'
type mockSteps_WriteConfig_Call struct {
	*mock.Call
}

// WriteConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSteps_Expecter) WriteConfig(ctx any) *mockSteps_WriteConfig_Call {
	return &mockSteps_WriteConfig_Call{Call: _e.mock.On("WriteConfig", ctx)}
}

func (_c *mockSteps_WriteConfig_Call) Run(run func(ctx context.Context)) *mockSteps_WriteConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockSteps_WriteConfig_Call) Return(undo Undo, err error) *mockSteps_WriteConfig_Call {
	_c.Call.Return(undo, err)
	return _c
}

func (_c *mockSteps_WriteConfig_Call) RunAndReturn(run func(ctx context.Context) (Undo, error)) *mockSteps_WriteConfig_Call {
	_c.Call.Return(run)
	return _c
}
