sonarr:
  main:
    base_url: http://sonarr:8989
    api_key: !secret SONARR_API_KEY

    delete_unmanaged_custom_formats:
      enabled: true
      ignore: []

    delete_unmanaged_quality_profiles:
      enabled: true
      ignore: []

    quality_definition:
      type: series

    root_folders:
      - /data/media/tvshows

    download_clients:
      data:
        - name: Deluge
          type: deluge
          enable: true
          priority: 1
          remove_completed_downloads: true
          remove_failed_downloads: true
          fields:
            host: gluetun
            port: 8112
            use_ssl: false
            password: !secret DELUGE_WEB_PASSWORD
            tv_category: tv-sonarr
            tv_imported_category: ""
            url_base: ""
            download_directory: ""
            completed_directory: ""
      update_password: true

    media_naming:
      episodes:
        rename: true

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p

    custom_formats: []

radarr:
  main:
    base_url: http://radarr:7878
    api_key: !secret RADARR_API_KEY

    delete_unmanaged_custom_formats:
      enabled: true
      ignore: []

    delete_unmanaged_quality_profiles:
      enabled: true
      ignore: []

    quality_definition:
      type: movie

    root_folders:
      - /data/media/movies

    download_clients:
      data:
        - name: Deluge
          type: deluge
          enable: true
          priority: 1
          remove_completed_downloads: false
          remove_failed_downloads: true
          fields:
            host: gluetun
            port: 8112
            use_ssl: false
            password: !secret DELUGE_WEB_PASSWORD
            movie_category: radarr
            movie_imported_category: ""
            url_base: ""
            download_directory: ""
            completed_directory: ""
      update_password: true

    media_naming:
      movie:
        rename: true

    include:
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web

    custom_formats: []
