// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package compose

import (
	"context"

	"github.com/compose-spec/compose-go/v2/types"
	"github.com/docker/compose/v5/pkg/api"
	"github.com/moby/moby/client"
	mock "github.com/stretchr/testify/mock"
)

// newMockService creates a new instance of mockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockService is an autogenerated mock type for the service type
type mockService struct {
	mock.Mock
}

type mockService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockService) EXPECT() *mockService_Expecter {
	return &mockService_Expecter{mock: &_m.Mock}
}

// Down provides a mock function for the type mockService
func (_mock *mockService) Down(ctx context.Context, projectName string, options api.DownOptions) error {
	ret := _mock.Called(ctx, projectName, options)

	if len(ret) == 0 {
		panic("no return value specified for Down")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.DownOptions) error); ok {
		r0 = returnFunc(ctx, projectName, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Down_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Down'
type mockService_Down_Call struct {
	*mock.Call
}

// Down is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
//   - options api.DownOptions
func (_e *mockService_Expecter) Down(ctx any, projectName any, options any) *mockService_Down_Call {
	return &mockService_Down_Call{Call: _e.mock.On("Down", ctx, projectName, options)}
}

func (_c *mockService_Down_Call) Run(run func(ctx context.Context, projectName string, options api.DownOptions)) *mockService_Down_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.DownOptions
		if args[2] != nil {
			arg2 = args[2].(api.DownOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Down_Call) Return(err error) *mockService_Down_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Down_Call) RunAndReturn(run func(ctx context.Context, projectName string, options api.DownOptions) error) *mockService_Down_Call {
	_c.Call.Return(run)
	return _c
}

// LoadProject provides a mock function for the type mockService
func (_mock *mockService) LoadProject(ctx context.Context, options api.ProjectLoadOptions) (*types.Project, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for LoadProject")
	}

	var r0 *types.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.ProjectLoadOptions) (*types.Project, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.ProjectLoadOptions) *types.Project); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, api.ProjectLoadOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockService_LoadProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadProject'
type mockService_LoadProject_Call struct {
	*mock.Call
}

// LoadProject is a helper method to define mock.On call
//   - ctx context.Context
//   - options api.ProjectLoadOptions
func (_e *mockService_Expecter) LoadProject(ctx any, options any) *mockService_LoadProject_Call {
	return &mockService_LoadProject_Call{Call: _e.mock.On("LoadProject", ctx, options)}
}

func (_c *mockService_LoadProject_Call) Run(run func(ctx context.Context, options api.ProjectLoadOptions)) *mockService_LoadProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 api.ProjectLoadOptions
		if args[1] != nil {
			arg1 = args[1].(api.ProjectLoadOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockService_LoadProject_Call) Return(project *types.Project, err error) *mockService_LoadProject_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *mockService_LoadProject_Call) RunAndReturn(run func(ctx context.Context, options api.ProjectLoadOptions) (*types.Project, error)) *mockService_LoadProject_Call {
	_c.Call.Return(run)
	return _c
}

// Logs provides a mock function for the type mockService
func (_mock *mockService) Logs(ctx context.Context, projectName string, consumer api.LogConsumer, options api.LogOptions) error {
	ret := _mock.Called(ctx, projectName, consumer, options)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.LogConsumer, api.LogOptions) error); ok {
		r0 = returnFunc(ctx, projectName, consumer, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type mockService_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
//   - consumer api.LogConsumer
//   - options api.LogOptions
func (_e *mockService_Expecter) Logs(ctx any, projectName any, consumer any, options any) *mockService_Logs_Call {
	return &mockService_Logs_Call{Call: _e.mock.On("Logs", ctx, projectName, consumer, options)}
}

func (_c *mockService_Logs_Call) Run(run func(ctx context.Context, projectName string, consumer api.LogConsumer, options api.LogOptions)) *mockService_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.LogConsumer
		if args[2] != nil {
			arg2 = args[2].(api.LogConsumer)
		}
		var arg3 api.LogOptions
		if args[3] != nil {
			arg3 = args[3].(api.LogOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockService_Logs_Call) Return(err error) *mockService_Logs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Logs_Call) RunAndReturn(run func(ctx context.Context, projectName string, consumer api.LogConsumer, options api.LogOptions) error) *mockService_Logs_Call {
	_c.Call.Return(run)
	return _c
}

// Ps provides a mock function for the type mockService
func (_mock *mockService) Ps(ctx context.Context, projectName string, options api.PsOptions) ([]api.ContainerSummary, error) {
	ret := _mock.Called(ctx, projectName, options)

	if len(ret) == 0 {
		panic("no return value specified for Ps")
	}

	var r0 []api.ContainerSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.PsOptions) ([]api.ContainerSummary, error)); ok {
		return returnFunc(ctx, projectName, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.PsOptions) []api.ContainerSummary); ok {
		r0 = returnFunc(ctx, projectName, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.ContainerSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, api.PsOptions) error); ok {
		r1 = returnFunc(ctx, projectName, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockService_Ps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ps'
type mockService_Ps_Call struct {
	*mock.Call
}

// Ps is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
//   - options api.PsOptions
func (_e *mockService_Expecter) Ps(ctx any, projectName any, options any) *mockService_Ps_Call {
	return &mockService_Ps_Call{Call: _e.mock.On("Ps", ctx, projectName, options)}
}

func (_c *mockService_Ps_Call) Run(run func(ctx context.Context, projectName string, options api.PsOptions)) *mockService_Ps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.PsOptions
		if args[2] != nil {
			arg2 = args[2].(api.PsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Ps_Call) Return(containerSummarys []api.ContainerSummary, err error) *mockService_Ps_Call {
	_c.Call.Return(containerSummarys, err)
	return _c
}

func (_c *mockService_Ps_Call) RunAndReturn(run func(ctx context.Context, projectName string, options api.PsOptions) ([]api.ContainerSummary, error)) *mockService_Ps_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function for the type mockService
func (_mock *mockService) Pull(ctx context.Context, project *types.Project, options api.PullOptions) error {
	ret := _mock.Called(ctx, project, options)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, api.PullOptions) error); ok {
		r0 = returnFunc(ctx, project, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type mockService_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - options api.PullOptions
func (_e *mockService_Expecter) Pull(ctx any, project any, options any) *mockService_Pull_Call {
	return &mockService_Pull_Call{Call: _e.mock.On("Pull", ctx, project, options)}
}

func (_c *mockService_Pull_Call) Run(run func(ctx context.Context, project *types.Project, options api.PullOptions)) *mockService_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 api.PullOptions
		if args[2] != nil {
			arg2 = args[2].(api.PullOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Pull_Call) Return(err error) *mockService_Pull_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Pull_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, options api.PullOptions) error) *mockService_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Restart provides a mock function for the type mockService
func (_mock *mockService) Restart(ctx context.Context, projectName string, options api.RestartOptions) error {
	ret := _mock.Called(ctx, projectName, options)

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.RestartOptions) error); ok {
		r0 = returnFunc(ctx, projectName, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type mockService_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
//   - options api.RestartOptions
func (_e *mockService_Expecter) Restart(ctx any, projectName any, options any) *mockService_Restart_Call {
	return &mockService_Restart_Call{Call: _e.mock.On("Restart", ctx, projectName, options)}
}

func (_c *mockService_Restart_Call) Run(run func(ctx context.Context, projectName string, options api.RestartOptions)) *mockService_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.RestartOptions
		if args[2] != nil {
			arg2 = args[2].(api.RestartOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Restart_Call) Return(err error) *mockService_Restart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Restart_Call) RunAndReturn(run func(ctx context.Context, projectName string, options api.RestartOptions) error) *mockService_Restart_Call {
	_c.Call.Return(run)
	return _c
}

// RunOneOffContainer provides a mock function for the type mockService
func (_mock *mockService) RunOneOffContainer(ctx context.Context, project *types.Project, options api.RunOptions) (int, error) {
	ret := _mock.Called(ctx, project, options)

	if len(ret) == 0 {
		panic("no return value specified for RunOneOffContainer")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, api.RunOptions) (int, error)); ok {
		return returnFunc(ctx, project, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, api.RunOptions) int); ok {
		r0 = returnFunc(ctx, project, options)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Project, api.RunOptions) error); ok {
		r1 = returnFunc(ctx, project, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockService_RunOneOffContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunOneOffContainer'
type mockService_RunOneOffContainer_Call struct {
	*mock.Call
}

// RunOneOffContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - options api.RunOptions
func (_e *mockService_Expecter) RunOneOffContainer(ctx any, project any, options any) *mockService_RunOneOffContainer_Call {
	return &mockService_RunOneOffContainer_Call{Call: _e.mock.On("RunOneOffContainer", ctx, project, options)}
}

func (_c *mockService_RunOneOffContainer_Call) Run(run func(ctx context.Context, project *types.Project, options api.RunOptions)) *mockService_RunOneOffContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 api.RunOptions
		if args[2] != nil {
			arg2 = args[2].(api.RunOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_RunOneOffContainer_Call) Return(n int, err error) *mockService_RunOneOffContainer_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockService_RunOneOffContainer_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, options api.RunOptions) (int, error)) *mockService_RunOneOffContainer_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type mockService
func (_mock *mockService) Start(ctx context.Context, projectName string, options api.StartOptions) error {
	ret := _mock.Called(ctx, projectName, options)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.StartOptions) error); ok {
		r0 = returnFunc(ctx, projectName, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mockService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
//   - options api.StartOptions
func (_e *mockService_Expecter) Start(ctx any, projectName any, options any) *mockService_Start_Call {
	return &mockService_Start_Call{Call: _e.mock.On("Start", ctx, projectName, options)}
}

func (_c *mockService_Start_Call) Run(run func(ctx context.Context, projectName string, options api.StartOptions)) *mockService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.StartOptions
		if args[2] != nil {
			arg2 = args[2].(api.StartOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Start_Call) Return(err error) *mockService_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Start_Call) RunAndReturn(run func(ctx context.Context, projectName string, options api.StartOptions) error) *mockService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type mockService
func (_mock *mockService) Stop(ctx context.Context, projectName string, options api.StopOptions) error {
	ret := _mock.Called(ctx, projectName, options)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.StopOptions) error); ok {
		r0 = returnFunc(ctx, projectName, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type mockService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
//   - options api.StopOptions
func (_e *mockService_Expecter) Stop(ctx any, projectName any, options any) *mockService_Stop_Call {
	return &mockService_Stop_Call{Call: _e.mock.On("Stop", ctx, projectName, options)}
}

func (_c *mockService_Stop_Call) Run(run func(ctx context.Context, projectName string, options api.StopOptions)) *mockService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.StopOptions
		if args[2] != nil {
			arg2 = args[2].(api.StopOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Stop_Call) Return(err error) *mockService_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Stop_Call) RunAndReturn(run func(ctx context.Context, projectName string, options api.StopOptions) error) *mockService_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type mockService
func (_mock *mockService) Up(ctx context.Context, project *types.Project, options api.UpOptions) error {
	ret := _mock.Called(ctx, project, options)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, api.UpOptions) error); ok {
		r0 = returnFunc(ctx, project, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type mockService_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - options api.UpOptions
func (_e *mockService_Expecter) Up(ctx any, project any, options any) *mockService_Up_Call {
	return &mockService_Up_Call{Call: _e.mock.On("Up", ctx, project, options)}
}

func (_c *mockService_Up_Call) Run(run func(ctx context.Context, project *types.Project, options api.UpOptions)) *mockService_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 api.UpOptions
		if args[2] != nil {
			arg2 = args[2].(api.UpOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Up_Call) Return(err error) *mockService_Up_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Up_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, options api.UpOptions) error) *mockService_Up_Call {
	_c.Call.Return(run)
	return _c
}

// newMockInspector creates a new instance of mockInspector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockInspector(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockInspector {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockInspector{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockInspector is an autogenerated mock type for the inspector type
type mockInspector struct {
	mock.Mock
}

type mockInspector_Expecter struct {
	mock *mock.Mock
}

func (_m *mockInspector) EXPECT() *mockInspector_Expecter {
	return &mockInspector_Expecter{mock: &_m.Mock}
}

// ContainerInspect provides a mock function for the type mockInspector
func (_mock *mockInspector) ContainerInspect(ctx context.Context, containerID string, options client.ContainerInspectOptions) (client.ContainerInspectResult, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerInspect")
	}

	var r0 client.ContainerInspectResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerInspectOptions) (client.ContainerInspectResult, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerInspectOptions) client.ContainerInspectResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerInspectResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerInspectOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockInspector_ContainerInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerInspect'
type mockInspector_ContainerInspect_Call struct {
	*mock.Call
}

// ContainerInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.ContainerInspectOptions
func (_e *mockInspector_Expecter) ContainerInspect(ctx any, containerID any, options any) *mockInspector_ContainerInspect_Call {
	return &mockInspector_ContainerInspect_Call{Call: _e.mock.On("ContainerInspect", ctx, containerID, options)}
}

func (_c *mockInspector_ContainerInspect_Call) Run(run func(ctx context.Context, containerID string, options client.ContainerInspectOptions)) *mockInspector_ContainerInspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerInspectOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerInspectOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockInspector_ContainerInspect_Call) Return(containerInspectResult client.ContainerInspectResult, err error) *mockInspector_ContainerInspect_Call {
	_c.Call.Return(containerInspectResult, err)
	return _c
}

func (_c *mockInspector_ContainerInspect_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.ContainerInspectOptions) (client.ContainerInspectResult, error)) *mockInspector_ContainerInspect_Call {
	_c.Call.Return(run)
	return _c
}
