// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package compose

import (
	"context"

	"github.com/compose-spec/compose-go/v2/types"
	"github.com/docker/compose/v5/pkg/api"
	"github.com/moby/moby/client"
	mock "github.com/stretchr/testify/mock"
)

// newMockService creates a new instance of mockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockService is an autogenerated mock type for the service type
type mockService struct {
	mock.Mock
}

type mockService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockService) EXPECT() *mockService_Expecter {
	return &mockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockService
func (_mock *mockService) Create(ctx context.Context, project *types.Project, options api.CreateOptions) error {
	ret := _mock.Called(ctx, project, options)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, api.CreateOptions) error); ok {
		r0 = returnFunc(ctx, project, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - options api.CreateOptions
func (_e *mockService_Expecter) Create(ctx any, project any, options any) *mockService_Create_Call {
	return &mockService_Create_Call{Call: _e.mock.On("Create", ctx, project, options)}
}

func (_c *mockService_Create_Call) Run(run func(ctx context.Context, project *types.Project, options api.CreateOptions)) *mockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 api.CreateOptions
		if args[2] != nil {
			arg2 = args[2].(api.CreateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Create_Call) Return(err error) *mockService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Create_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, options api.CreateOptions) error) *mockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Down provides a mock function for the type mockService
func (_mock *mockService) Down(ctx context.Context, projectName string, options api.DownOptions) error {
	ret := _mock.Called(ctx, projectName, options)

	if len(ret) == 0 {
		panic("no return value specified for Down")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.DownOptions) error); ok {
		r0 = returnFunc(ctx, projectName, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Down_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Down'
type mockService_Down_Call struct {
	*mock.Call
}

// Down is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
//   - options api.DownOptions
func (_e *mockService_Expecter) Down(ctx any, projectName any, options any) *mockService_Down_Call {
	return &mockService_Down_Call{Call: _e.mock.On("Down", ctx, projectName, options)}
}

func (_c *mockService_Down_Call) Run(run func(ctx context.Context, projectName string, options api.DownOptions)) *mockService_Down_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.DownOptions
		if args[2] != nil {
			arg2 = args[2].(api.DownOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Down_Call) Return(err error) *mockService_Down_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Down_Call) RunAndReturn(run func(ctx context.Context, projectName string, options api.DownOptions) error) *mockService_Down_Call {
	_c.Call.Return(run)
	return _c
}

// LoadProject provides a mock function for the type mockService
func (_mock *mockService) LoadProject(ctx context.Context, options api.ProjectLoadOptions) (*types.Project, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for LoadProject")
	}

	var r0 *types.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.ProjectLoadOptions) (*types.Project, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.ProjectLoadOptions) *types.Project); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, api.ProjectLoadOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockService_LoadProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadProject'
type mockService_LoadProject_Call struct {
	*mock.Call
}

// LoadProject is a helper method to define mock.On call
//   - ctx context.Context
//   - options api.ProjectLoadOptions
func (_e *mockService_Expecter) LoadProject(ctx any, options any) *mockService_LoadProject_Call {
	return &mockService_LoadProject_Call{Call: _e.mock.On("LoadProject", ctx, options)}
}

func (_c *mockService_LoadProject_Call) Run(run func(ctx context.Context, options api.ProjectLoadOptions)) *mockService_LoadProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 api.ProjectLoadOptions
		if args[1] != nil {
			arg1 = args[1].(api.ProjectLoadOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockService_LoadProject_Call) Return(project *types.Project, err error) *mockService_LoadProject_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *mockService_LoadProject_Call) RunAndReturn(run func(ctx context.Context, options api.ProjectLoadOptions) (*types.Project, error)) *mockService_LoadProject_Call {
	_c.Call.Return(run)
	return _c
}

// Logs provides a mock function for the type mockService
func (_mock *mockService) Logs(ctx context.Context, projectName string, consumer api.LogConsumer, options api.LogOptions) error {
	ret := _mock.Called(ctx, projectName, consumer, options)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.LogConsumer, api.LogOptions) error); ok {
		r0 = returnFunc(ctx, projectName, consumer, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type mockService_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
//   - consumer api.LogConsumer
//   - options api.LogOptions
func (_e *mockService_Expecter) Logs(ctx any, projectName any, consumer any, options any) *mockService_Logs_Call {
	return &mockService_Logs_Call{Call: _e.mock.On("Logs", ctx, projectName, consumer, options)}
}

func (_c *mockService_Logs_Call) Run(run func(ctx context.Context, projectName string, consumer api.LogConsumer, options api.LogOptions)) *mockService_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.LogConsumer
		if args[2] != nil {
			arg2 = args[2].(api.LogConsumer)
		}
		var arg3 api.LogOptions
		if args[3] != nil {
			arg3 = args[3].(api.LogOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockService_Logs_Call) Return(err error) *mockService_Logs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Logs_Call) RunAndReturn(run func(ctx context.Context, projectName string, consumer api.LogConsumer, options api.LogOptions) error) *mockService_Logs_Call {
	_c.Call.Return(run)
	return _c
}

// Ps provides a mock function for the type mockService
func (_mock *mockService) Ps(ctx context.Context, projectName string, options api.PsOptions) ([]api.ContainerSummary, error) {
	ret := _mock.Called(ctx, projectName, options)

	if len(ret) == 0 {
		panic("no return value specified for Ps")
	}

	var r0 []api.ContainerSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.PsOptions) ([]api.ContainerSummary, error)); ok {
		return returnFunc(ctx, projectName, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.PsOptions) []api.ContainerSummary); ok {
		r0 = returnFunc(ctx, projectName, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.ContainerSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, api.PsOptions) error); ok {
		r1 = returnFunc(ctx, projectName, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockService_Ps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ps'
type mockService_Ps_Call struct {
	*mock.Call
}

// Ps is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
//   - options api.PsOptions
func (_e *mockService_Expecter) Ps(ctx any, projectName any, options any) *mockService_Ps_Call {
	return &mockService_Ps_Call{Call: _e.mock.On("Ps", ctx, projectName, options)}
}

func (_c *mockService_Ps_Call) Run(run func(ctx context.Context, projectName string, options api.PsOptions)) *mockService_Ps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.PsOptions
		if args[2] != nil {
			arg2 = args[2].(api.PsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Ps_Call) Return(containerSummarys []api.ContainerSummary, err error) *mockService_Ps_Call {
	_c.Call.Return(containerSummarys, err)
	return _c
}

func (_c *mockService_Ps_Call) RunAndReturn(run func(ctx context.Context, projectName string, options api.PsOptions) ([]api.ContainerSummary, error)) *mockService_Ps_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function for the type mockService
func (_mock *mockService) Pull(ctx context.Context, project *types.Project, options api.PullOptions) error {
	ret := _mock.Called(ctx, project, options)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, api.PullOptions) error); ok {
		r0 = returnFunc(ctx, project, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type mockService_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - options api.PullOptions
func (_e *mockService_Expecter) Pull(ctx any, project any, options any) *mockService_Pull_Call {
	return &mockService_Pull_Call{Call: _e.mock.On("Pull", ctx, project, options)}
}

func (_c *mockService_Pull_Call) Run(run func(ctx context.Context, project *types.Project, options api.PullOptions)) *mockService_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 api.PullOptions
		if args[2] != nil {
			arg2 = args[2].(api.PullOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Pull_Call) Return(err error) *mockService_Pull_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Pull_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, options api.PullOptions) error) *mockService_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Restart provides a mock function for the type mockService
func (_mock *mockService) Restart(ctx context.Context, projectName string, options api.RestartOptions) error {
	ret := _mock.Called(ctx, projectName, options)

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.RestartOptions) error); ok {
		r0 = returnFunc(ctx, projectName, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type mockService_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
//   - options api.RestartOptions
func (_e *mockService_Expecter) Restart(ctx any, projectName any, options any) *mockService_Restart_Call {
	return &mockService_Restart_Call{Call: _e.mock.On("Restart", ctx, projectName, options)}
}

func (_c *mockService_Restart_Call) Run(run func(ctx context.Context, projectName string, options api.RestartOptions)) *mockService_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.RestartOptions
		if args[2] != nil {
			arg2 = args[2].(api.RestartOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Restart_Call) Return(err error) *mockService_Restart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Restart_Call) RunAndReturn(run func(ctx context.Context, projectName string, options api.RestartOptions) error) *mockService_Restart_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type mockService
func (_mock *mockService) Start(ctx context.Context, projectName string, options api.StartOptions) error {
	ret := _mock.Called(ctx, projectName, options)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.StartOptions) error); ok {
		r0 = returnFunc(ctx, projectName, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mockService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
//   - options api.StartOptions
func (_e *mockService_Expecter) Start(ctx any, projectName any, options any) *mockService_Start_Call {
	return &mockService_Start_Call{Call: _e.mock.On("Start", ctx, projectName, options)}
}

func (_c *mockService_Start_Call) Run(run func(ctx context.Context, projectName string, options api.StartOptions)) *mockService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.StartOptions
		if args[2] != nil {
			arg2 = args[2].(api.StartOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Start_Call) Return(err error) *mockService_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Start_Call) RunAndReturn(run func(ctx context.Context, projectName string, options api.StartOptions) error) *mockService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type mockService
func (_mock *mockService) Stop(ctx context.Context, projectName string, options api.StopOptions) error {
	ret := _mock.Called(ctx, projectName, options)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api.StopOptions) error); ok {
		r0 = returnFunc(ctx, projectName, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type mockService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
//   - options api.StopOptions
func (_e *mockService_Expecter) Stop(ctx any, projectName any, options any) *mockService_Stop_Call {
	return &mockService_Stop_Call{Call: _e.mock.On("Stop", ctx, projectName, options)}
}

func (_c *mockService_Stop_Call) Run(run func(ctx context.Context, projectName string, options api.StopOptions)) *mockService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.StopOptions
		if args[2] != nil {
			arg2 = args[2].(api.StopOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Stop_Call) Return(err error) *mockService_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Stop_Call) RunAndReturn(run func(ctx context.Context, projectName string, options api.StopOptions) error) *mockService_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type mockService
func (_mock *mockService) Up(ctx context.Context, project *types.Project, options api.UpOptions) error {
	ret := _mock.Called(ctx, project, options)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, api.UpOptions) error); ok {
		r0 = returnFunc(ctx, project, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockService_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type mockService_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - options api.UpOptions
func (_e *mockService_Expecter) Up(ctx any, project any, options any) *mockService_Up_Call {
	return &mockService_Up_Call{Call: _e.mock.On("Up", ctx, project, options)}
}

func (_c *mockService_Up_Call) Run(run func(ctx context.Context, project *types.Project, options api.UpOptions)) *mockService_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 api.UpOptions
		if args[2] != nil {
			arg2 = args[2].(api.UpOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockService_Up_Call) Return(err error) *mockService_Up_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockService_Up_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, options api.UpOptions) error) *mockService_Up_Call {
	_c.Call.Return(run)
	return _c
}

// newMockContainers creates a new instance of mockContainers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockContainers(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockContainers {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockContainers{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockContainers is an autogenerated mock type for the containers type
type mockContainers struct {
	mock.Mock
}

type mockContainers_Expecter struct {
	mock *mock.Mock
}

func (_m *mockContainers) EXPECT() *mockContainers_Expecter {
	return &mockContainers_Expecter{mock: &_m.Mock}
}

// ContainerInspect provides a mock function for the type mockContainers
func (_mock *mockContainers) ContainerInspect(ctx context.Context, containerID string, options client.ContainerInspectOptions) (client.ContainerInspectResult, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerInspect")
	}

	var r0 client.ContainerInspectResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerInspectOptions) (client.ContainerInspectResult, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerInspectOptions) client.ContainerInspectResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerInspectResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerInspectOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockContainers_ContainerInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerInspect'
type mockContainers_ContainerInspect_Call struct {
	*mock.Call
}

// ContainerInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.ContainerInspectOptions
func (_e *mockContainers_Expecter) ContainerInspect(ctx any, containerID any, options any) *mockContainers_ContainerInspect_Call {
	return &mockContainers_ContainerInspect_Call{Call: _e.mock.On("ContainerInspect", ctx, containerID, options)}
}

func (_c *mockContainers_ContainerInspect_Call) Run(run func(ctx context.Context, containerID string, options client.ContainerInspectOptions)) *mockContainers_ContainerInspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerInspectOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerInspectOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockContainers_ContainerInspect_Call) Return(containerInspectResult client.ContainerInspectResult, err error) *mockContainers_ContainerInspect_Call {
	_c.Call.Return(containerInspectResult, err)
	return _c
}

func (_c *mockContainers_ContainerInspect_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.ContainerInspectOptions) (client.ContainerInspectResult, error)) *mockContainers_ContainerInspect_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerLogs provides a mock function for the type mockContainers
func (_mock *mockContainers) ContainerLogs(ctx context.Context, containerID string, options client.ContainerLogsOptions) (client.ContainerLogsResult, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerLogs")
	}

	var r0 client.ContainerLogsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerLogsOptions) (client.ContainerLogsResult, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerLogsOptions) client.ContainerLogsResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ContainerLogsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerLogsOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockContainers_ContainerLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerLogs'
type mockContainers_ContainerLogs_Call struct {
	*mock.Call
}

// ContainerLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.ContainerLogsOptions
func (_e *mockContainers_Expecter) ContainerLogs(ctx any, containerID any, options any) *mockContainers_ContainerLogs_Call {
	return &mockContainers_ContainerLogs_Call{Call: _e.mock.On("ContainerLogs", ctx, containerID, options)}
}

func (_c *mockContainers_ContainerLogs_Call) Run(run func(ctx context.Context, containerID string, options client.ContainerLogsOptions)) *mockContainers_ContainerLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerLogsOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerLogsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockContainers_ContainerLogs_Call) Return(containerLogsResult client.ContainerLogsResult, err error) *mockContainers_ContainerLogs_Call {
	_c.Call.Return(containerLogsResult, err)
	return _c
}

func (_c *mockContainers_ContainerLogs_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.ContainerLogsOptions) (client.ContainerLogsResult, error)) *mockContainers_ContainerLogs_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerRemove provides a mock function for the type mockContainers
func (_mock *mockContainers) ContainerRemove(ctx context.Context, containerID string, options client.ContainerRemoveOptions) (client.ContainerRemoveResult, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerRemove")
	}

	var r0 client.ContainerRemoveResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerRemoveOptions) (client.ContainerRemoveResult, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerRemoveOptions) client.ContainerRemoveResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerRemoveResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerRemoveOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockContainers_ContainerRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerRemove'
type mockContainers_ContainerRemove_Call struct {
	*mock.Call
}

// ContainerRemove is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.ContainerRemoveOptions
func (_e *mockContainers_Expecter) ContainerRemove(ctx any, containerID any, options any) *mockContainers_ContainerRemove_Call {
	return &mockContainers_ContainerRemove_Call{Call: _e.mock.On("ContainerRemove", ctx, containerID, options)}
}

func (_c *mockContainers_ContainerRemove_Call) Run(run func(ctx context.Context, containerID string, options client.ContainerRemoveOptions)) *mockContainers_ContainerRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerRemoveOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerRemoveOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockContainers_ContainerRemove_Call) Return(containerRemoveResult client.ContainerRemoveResult, err error) *mockContainers_ContainerRemove_Call {
	_c.Call.Return(containerRemoveResult, err)
	return _c
}

func (_c *mockContainers_ContainerRemove_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.ContainerRemoveOptions) (client.ContainerRemoveResult, error)) *mockContainers_ContainerRemove_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerStart provides a mock function for the type mockContainers
func (_mock *mockContainers) ContainerStart(ctx context.Context, containerID string, options client.ContainerStartOptions) (client.ContainerStartResult, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStart")
	}

	var r0 client.ContainerStartResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStartOptions) (client.ContainerStartResult, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStartOptions) client.ContainerStartResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerStartResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerStartOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockContainers_ContainerStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStart'
type mockContainers_ContainerStart_Call struct {
	*mock.Call
}

// ContainerStart is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.ContainerStartOptions
func (_e *mockContainers_Expecter) ContainerStart(ctx any, containerID any, options any) *mockContainers_ContainerStart_Call {
	return &mockContainers_ContainerStart_Call{Call: _e.mock.On("ContainerStart", ctx, containerID, options)}
}

func (_c *mockContainers_ContainerStart_Call) Run(run func(ctx context.Context, containerID string, options client.ContainerStartOptions)) *mockContainers_ContainerStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerStartOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerStartOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockContainers_ContainerStart_Call) Return(containerStartResult client.ContainerStartResult, err error) *mockContainers_ContainerStart_Call {
	_c.Call.Return(containerStartResult, err)
	return _c
}

func (_c *mockContainers_ContainerStart_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.ContainerStartOptions) (client.ContainerStartResult, error)) *mockContainers_ContainerStart_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerStop provides a mock function for the type mockContainers
func (_mock *mockContainers) ContainerStop(ctx context.Context, containerID string, options client.ContainerStopOptions) (client.ContainerStopResult, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStop")
	}

	var r0 client.ContainerStopResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStopOptions) (client.ContainerStopResult, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStopOptions) client.ContainerStopResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerStopResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerStopOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockContainers_ContainerStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStop'
type mockContainers_ContainerStop_Call struct {
	*mock.Call
}

// ContainerStop is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.ContainerStopOptions
func (_e *mockContainers_Expecter) ContainerStop(ctx any, containerID any, options any) *mockContainers_ContainerStop_Call {
	return &mockContainers_ContainerStop_Call{Call: _e.mock.On("ContainerStop", ctx, containerID, options)}
}

func (_c *mockContainers_ContainerStop_Call) Run(run func(ctx context.Context, containerID string, options client.ContainerStopOptions)) *mockContainers_ContainerStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerStopOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerStopOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockContainers_ContainerStop_Call) Return(containerStopResult client.ContainerStopResult, err error) *mockContainers_ContainerStop_Call {
	_c.Call.Return(containerStopResult, err)
	return _c
}

func (_c *mockContainers_ContainerStop_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.ContainerStopOptions) (client.ContainerStopResult, error)) *mockContainers_ContainerStop_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerWait provides a mock function for the type mockContainers
func (_mock *mockContainers) ContainerWait(ctx context.Context, containerID string, options client.ContainerWaitOptions) client.ContainerWaitResult {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerWait")
	}

	var r0 client.ContainerWaitResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerWaitOptions) client.ContainerWaitResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerWaitResult)
	}
	return r0
}

// mockContainers_ContainerWait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerWait'
type mockContainers_ContainerWait_Call struct {
	*mock.Call
}

// ContainerWait is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.ContainerWaitOptions
func (_e *mockContainers_Expecter) ContainerWait(ctx any, containerID any, options any) *mockContainers_ContainerWait_Call {
	return &mockContainers_ContainerWait_Call{Call: _e.mock.On("ContainerWait", ctx, containerID, options)}
}

func (_c *mockContainers_ContainerWait_Call) Run(run func(ctx context.Context, containerID string, options client.ContainerWaitOptions)) *mockContainers_ContainerWait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerWaitOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerWaitOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockContainers_ContainerWait_Call) Return(containerWaitResult client.ContainerWaitResult) *mockContainers_ContainerWait_Call {
	_c.Call.Return(containerWaitResult)
	return _c
}

func (_c *mockContainers_ContainerWait_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.ContainerWaitOptions) client.ContainerWaitResult) *mockContainers_ContainerWait_Call {
	_c.Call.Return(run)
	return _c
}

// ImageInspect provides a mock function for the type mockContainers
func (_mock *mockContainers) ImageInspect(ctx context.Context, image string, options ...client.ImageInspectOption) (client.ImageInspectResult, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, image, options)
	} else {
		tmpRet = _mock.Called(ctx, image)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ImageInspect")
	}

	var r0 client.ImageInspectResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.ImageInspectOption) (client.ImageInspectResult, error)); ok {
		return returnFunc(ctx, image, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.ImageInspectOption) client.ImageInspectResult); ok {
		r0 = returnFunc(ctx, image, options...)
	} else {
		r0 = ret.Get(0).(client.ImageInspectResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.ImageInspectOption) error); ok {
		r1 = returnFunc(ctx, image, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockContainers_ImageInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageInspect'
type mockContainers_ImageInspect_Call struct {
	*mock.Call
}

// ImageInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
//   - options ...client.ImageInspectOption
func (_e *mockContainers_Expecter) ImageInspect(ctx any, image any, options ...any) *mockContainers_ImageInspect_Call {
	return &mockContainers_ImageInspect_Call{Call: _e.mock.On("ImageInspect",
		append([]any{ctx, image}, options...)...)}
}

func (_c *mockContainers_ImageInspect_Call) Run(run func(ctx context.Context, image string, options ...client.ImageInspectOption)) *mockContainers_ImageInspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.ImageInspectOption
		var variadicArgs []client.ImageInspectOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.ImageInspectOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockContainers_ImageInspect_Call) Return(imageInspectResult client.ImageInspectResult, err error) *mockContainers_ImageInspect_Call {
	_c.Call.Return(imageInspectResult, err)
	return _c
}

func (_c *mockContainers_ImageInspect_Call) RunAndReturn(run func(ctx context.Context, image string, options ...client.ImageInspectOption) (client.ImageInspectResult, error)) *mockContainers_ImageInspect_Call {
	_c.Call.Return(run)
	return _c
}
