title: "@INSTALLATION_NAME@"
headerStyle: clean
statusStyle: dot
hideVersion: true
disableUpdateCheck: true
layout:
  - Downloads:
      header: false
      style: row
      columns: 2
  - Coming up:
      style: column
  - Watch:
      style: column
  - Library:
      style: row
      columns: 2
  - Maintenance:
      style: row
      columns: 3
