title: "@INSTALLATION_NAME@"
headerStyle: boxed
statusStyle: dot
hideVersion: true
disableUpdateCheck: true
layout:
  - Healthchecks:
      style: row
      columns: 3
      header: false
  - Coming up:
      style: column
  - Watch:
      style: column
  - Downloads:
      style: columns
  - Library:
      style: columns
  - Maintenance:
      style: columns
