// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wiring

import (
	"context"

	"github.com/moby/moby/client"
	mock "github.com/stretchr/testify/mock"
)

// newMockDocker creates a new instance of mockDocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDocker {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockDocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockDocker is an autogenerated mock type for the Docker type
type mockDocker struct {
	mock.Mock
}

type mockDocker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDocker) EXPECT() *mockDocker_Expecter {
	return &mockDocker_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type mockDocker
func (_mock *mockDocker) Exec(ctx context.Context, container string, user string, command []string) (string, error) {
	ret := _mock.Called(ctx, container, user, command)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) (string, error)); ok {
		return returnFunc(ctx, container, user, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) string); ok {
		r0 = returnFunc(ctx, container, user, command)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = returnFunc(ctx, container, user, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDocker_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type mockDocker_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - container string
//   - user string
//   - command []string
func (_e *mockDocker_Expecter) Exec(ctx any, container any, user any, command any) *mockDocker_Exec_Call {
	return &mockDocker_Exec_Call{Call: _e.mock.On("Exec", ctx, container, user, command)}
}

func (_c *mockDocker_Exec_Call) Run(run func(ctx context.Context, container string, user string, command []string)) *mockDocker_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockDocker_Exec_Call) Return(s string, err error) *mockDocker_Exec_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockDocker_Exec_Call) RunAndReturn(run func(ctx context.Context, container string, user string, command []string) (string, error)) *mockDocker_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type mockDocker
func (_mock *mockDocker) Start(ctx context.Context, container string) error {
	ret := _mock.Called(ctx, container)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, container)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockDocker_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mockDocker_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - container string
func (_e *mockDocker_Expecter) Start(ctx any, container any) *mockDocker_Start_Call {
	return &mockDocker_Start_Call{Call: _e.mock.On("Start", ctx, container)}
}

func (_c *mockDocker_Start_Call) Run(run func(ctx context.Context, container string)) *mockDocker_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockDocker_Start_Call) Return(err error) *mockDocker_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockDocker_Start_Call) RunAndReturn(run func(ctx context.Context, container string) error) *mockDocker_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type mockDocker
func (_mock *mockDocker) Stop(ctx context.Context, container string) error {
	ret := _mock.Called(ctx, container)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, container)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockDocker_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type mockDocker_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - container string
func (_e *mockDocker_Expecter) Stop(ctx any, container any) *mockDocker_Stop_Call {
	return &mockDocker_Stop_Call{Call: _e.mock.On("Stop", ctx, container)}
}

func (_c *mockDocker_Stop_Call) Run(run func(ctx context.Context, container string)) *mockDocker_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockDocker_Stop_Call) Return(err error) *mockDocker_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockDocker_Stop_Call) RunAndReturn(run func(ctx context.Context, container string) error) *mockDocker_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDockerAPI creates a new instance of mockDockerAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDockerAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDockerAPI {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockDockerAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockDockerAPI is an autogenerated mock type for the dockerAPI type
type mockDockerAPI struct {
	mock.Mock
}

type mockDockerAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDockerAPI) EXPECT() *mockDockerAPI_Expecter {
	return &mockDockerAPI_Expecter{mock: &_m.Mock}
}

// ContainerStart provides a mock function for the type mockDockerAPI
func (_mock *mockDockerAPI) ContainerStart(ctx context.Context, container string, options client.ContainerStartOptions) (client.ContainerStartResult, error) {
	ret := _mock.Called(ctx, container, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStart")
	}

	var r0 client.ContainerStartResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStartOptions) (client.ContainerStartResult, error)); ok {
		return returnFunc(ctx, container, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStartOptions) client.ContainerStartResult); ok {
		r0 = returnFunc(ctx, container, options)
	} else {
		r0 = ret.Get(0).(client.ContainerStartResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerStartOptions) error); ok {
		r1 = returnFunc(ctx, container, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDockerAPI_ContainerStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStart'
type mockDockerAPI_ContainerStart_Call struct {
	*mock.Call
}

// ContainerStart is a helper method to define mock.On call
//   - ctx context.Context
//   - container string
//   - options client.ContainerStartOptions
func (_e *mockDockerAPI_Expecter) ContainerStart(ctx any, container any, options any) *mockDockerAPI_ContainerStart_Call {
	return &mockDockerAPI_ContainerStart_Call{Call: _e.mock.On("ContainerStart", ctx, container, options)}
}

func (_c *mockDockerAPI_ContainerStart_Call) Run(run func(ctx context.Context, container string, options client.ContainerStartOptions)) *mockDockerAPI_ContainerStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerStartOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerStartOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockDockerAPI_ContainerStart_Call) Return(containerStartResult client.ContainerStartResult, err error) *mockDockerAPI_ContainerStart_Call {
	_c.Call.Return(containerStartResult, err)
	return _c
}

func (_c *mockDockerAPI_ContainerStart_Call) RunAndReturn(run func(ctx context.Context, container string, options client.ContainerStartOptions) (client.ContainerStartResult, error)) *mockDockerAPI_ContainerStart_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerStop provides a mock function for the type mockDockerAPI
func (_mock *mockDockerAPI) ContainerStop(ctx context.Context, container string, options client.ContainerStopOptions) (client.ContainerStopResult, error) {
	ret := _mock.Called(ctx, container, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStop")
	}

	var r0 client.ContainerStopResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStopOptions) (client.ContainerStopResult, error)); ok {
		return returnFunc(ctx, container, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStopOptions) client.ContainerStopResult); ok {
		r0 = returnFunc(ctx, container, options)
	} else {
		r0 = ret.Get(0).(client.ContainerStopResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerStopOptions) error); ok {
		r1 = returnFunc(ctx, container, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDockerAPI_ContainerStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStop'
type mockDockerAPI_ContainerStop_Call struct {
	*mock.Call
}

// ContainerStop is a helper method to define mock.On call
//   - ctx context.Context
//   - container string
//   - options client.ContainerStopOptions
func (_e *mockDockerAPI_Expecter) ContainerStop(ctx any, container any, options any) *mockDockerAPI_ContainerStop_Call {
	return &mockDockerAPI_ContainerStop_Call{Call: _e.mock.On("ContainerStop", ctx, container, options)}
}

func (_c *mockDockerAPI_ContainerStop_Call) Run(run func(ctx context.Context, container string, options client.ContainerStopOptions)) *mockDockerAPI_ContainerStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerStopOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerStopOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockDockerAPI_ContainerStop_Call) Return(containerStopResult client.ContainerStopResult, err error) *mockDockerAPI_ContainerStop_Call {
	_c.Call.Return(containerStopResult, err)
	return _c
}

func (_c *mockDockerAPI_ContainerStop_Call) RunAndReturn(run func(ctx context.Context, container string, options client.ContainerStopOptions) (client.ContainerStopResult, error)) *mockDockerAPI_ContainerStop_Call {
	_c.Call.Return(run)
	return _c
}

// ExecAttach provides a mock function for the type mockDockerAPI
func (_mock *mockDockerAPI) ExecAttach(ctx context.Context, execID string, options client.ExecAttachOptions) (client.ExecAttachResult, error) {
	ret := _mock.Called(ctx, execID, options)

	if len(ret) == 0 {
		panic("no return value specified for ExecAttach")
	}

	var r0 client.ExecAttachResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ExecAttachOptions) (client.ExecAttachResult, error)); ok {
		return returnFunc(ctx, execID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ExecAttachOptions) client.ExecAttachResult); ok {
		r0 = returnFunc(ctx, execID, options)
	} else {
		r0 = ret.Get(0).(client.ExecAttachResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ExecAttachOptions) error); ok {
		r1 = returnFunc(ctx, execID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDockerAPI_ExecAttach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecAttach'
type mockDockerAPI_ExecAttach_Call struct {
	*mock.Call
}

// ExecAttach is a helper method to define mock.On call
//   - ctx context.Context
//   - execID string
//   - options client.ExecAttachOptions
func (_e *mockDockerAPI_Expecter) ExecAttach(ctx any, execID any, options any) *mockDockerAPI_ExecAttach_Call {
	return &mockDockerAPI_ExecAttach_Call{Call: _e.mock.On("ExecAttach", ctx, execID, options)}
}

func (_c *mockDockerAPI_ExecAttach_Call) Run(run func(ctx context.Context, execID string, options client.ExecAttachOptions)) *mockDockerAPI_ExecAttach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ExecAttachOptions
		if args[2] != nil {
			arg2 = args[2].(client.ExecAttachOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockDockerAPI_ExecAttach_Call) Return(execAttachResult client.ExecAttachResult, err error) *mockDockerAPI_ExecAttach_Call {
	_c.Call.Return(execAttachResult, err)
	return _c
}

func (_c *mockDockerAPI_ExecAttach_Call) RunAndReturn(run func(ctx context.Context, execID string, options client.ExecAttachOptions) (client.ExecAttachResult, error)) *mockDockerAPI_ExecAttach_Call {
	_c.Call.Return(run)
	return _c
}

// ExecCreate provides a mock function for the type mockDockerAPI
func (_mock *mockDockerAPI) ExecCreate(ctx context.Context, container string, options client.ExecCreateOptions) (client.ExecCreateResult, error) {
	ret := _mock.Called(ctx, container, options)

	if len(ret) == 0 {
		panic("no return value specified for ExecCreate")
	}

	var r0 client.ExecCreateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ExecCreateOptions) (client.ExecCreateResult, error)); ok {
		return returnFunc(ctx, container, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ExecCreateOptions) client.ExecCreateResult); ok {
		r0 = returnFunc(ctx, container, options)
	} else {
		r0 = ret.Get(0).(client.ExecCreateResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ExecCreateOptions) error); ok {
		r1 = returnFunc(ctx, container, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDockerAPI_ExecCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecCreate'
type mockDockerAPI_ExecCreate_Call struct {
	*mock.Call
}

// ExecCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - container string
//   - options client.ExecCreateOptions
func (_e *mockDockerAPI_Expecter) ExecCreate(ctx any, container any, options any) *mockDockerAPI_ExecCreate_Call {
	return &mockDockerAPI_ExecCreate_Call{Call: _e.mock.On("ExecCreate", ctx, container, options)}
}

func (_c *mockDockerAPI_ExecCreate_Call) Run(run func(ctx context.Context, container string, options client.ExecCreateOptions)) *mockDockerAPI_ExecCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ExecCreateOptions
		if args[2] != nil {
			arg2 = args[2].(client.ExecCreateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockDockerAPI_ExecCreate_Call) Return(execCreateResult client.ExecCreateResult, err error) *mockDockerAPI_ExecCreate_Call {
	_c.Call.Return(execCreateResult, err)
	return _c
}

func (_c *mockDockerAPI_ExecCreate_Call) RunAndReturn(run func(ctx context.Context, container string, options client.ExecCreateOptions) (client.ExecCreateResult, error)) *mockDockerAPI_ExecCreate_Call {
	_c.Call.Return(run)
	return _c
}

// ExecInspect provides a mock function for the type mockDockerAPI
func (_mock *mockDockerAPI) ExecInspect(ctx context.Context, execID string, options client.ExecInspectOptions) (client.ExecInspectResult, error) {
	ret := _mock.Called(ctx, execID, options)

	if len(ret) == 0 {
		panic("no return value specified for ExecInspect")
	}

	var r0 client.ExecInspectResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ExecInspectOptions) (client.ExecInspectResult, error)); ok {
		return returnFunc(ctx, execID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ExecInspectOptions) client.ExecInspectResult); ok {
		r0 = returnFunc(ctx, execID, options)
	} else {
		r0 = ret.Get(0).(client.ExecInspectResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ExecInspectOptions) error); ok {
		r1 = returnFunc(ctx, execID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDockerAPI_ExecInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecInspect'
type mockDockerAPI_ExecInspect_Call struct {
	*mock.Call
}

// ExecInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - execID string
//   - options client.ExecInspectOptions
func (_e *mockDockerAPI_Expecter) ExecInspect(ctx any, execID any, options any) *mockDockerAPI_ExecInspect_Call {
	return &mockDockerAPI_ExecInspect_Call{Call: _e.mock.On("ExecInspect", ctx, execID, options)}
}

func (_c *mockDockerAPI_ExecInspect_Call) Run(run func(ctx context.Context, execID string, options client.ExecInspectOptions)) *mockDockerAPI_ExecInspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ExecInspectOptions
		if args[2] != nil {
			arg2 = args[2].(client.ExecInspectOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockDockerAPI_ExecInspect_Call) Return(execInspectResult client.ExecInspectResult, err error) *mockDockerAPI_ExecInspect_Call {
	_c.Call.Return(execInspectResult, err)
	return _c
}

func (_c *mockDockerAPI_ExecInspect_Call) RunAndReturn(run func(ctx context.Context, execID string, options client.ExecInspectOptions) (client.ExecInspectResult, error)) *mockDockerAPI_ExecInspect_Call {
	_c.Call.Return(run)
	return _c
}
