// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package images

import (
	"context"

	"github.com/moby/moby/client"
	mock "github.com/stretchr/testify/mock"
)

// newMockClient creates a new instance of mockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockClient is an autogenerated mock type for the Client type
type mockClient struct {
	mock.Mock
}

type mockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockClient) EXPECT() *mockClient_Expecter {
	return &mockClient_Expecter{mock: &_m.Mock}
}

// ImageList provides a mock function for the type mockClient
func (_mock *mockClient) ImageList(ctx context.Context, options client.ImageListOptions) (client.ImageListResult, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ImageList")
	}

	var r0 client.ImageListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ImageListOptions) (client.ImageListResult, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ImageListOptions) client.ImageListResult); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Get(0).(client.ImageListResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.ImageListOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockClient_ImageList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageList'
type mockClient_ImageList_Call struct {
	*mock.Call
}

// ImageList is a helper method to define mock.On call
//   - ctx context.Context
//   - options client.ImageListOptions
func (_e *mockClient_Expecter) ImageList(ctx any, options any) *mockClient_ImageList_Call {
	return &mockClient_ImageList_Call{Call: _e.mock.On("ImageList", ctx, options)}
}

func (_c *mockClient_ImageList_Call) Run(run func(ctx context.Context, options client.ImageListOptions)) *mockClient_ImageList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ImageListOptions
		if args[1] != nil {
			arg1 = args[1].(client.ImageListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockClient_ImageList_Call) Return(imageListResult client.ImageListResult, err error) *mockClient_ImageList_Call {
	_c.Call.Return(imageListResult, err)
	return _c
}

func (_c *mockClient_ImageList_Call) RunAndReturn(run func(ctx context.Context, options client.ImageListOptions) (client.ImageListResult, error)) *mockClient_ImageList_Call {
	_c.Call.Return(run)
	return _c
}

// ImageRemove provides a mock function for the type mockClient
func (_mock *mockClient) ImageRemove(ctx context.Context, image string, options client.ImageRemoveOptions) (client.ImageRemoveResult, error) {
	ret := _mock.Called(ctx, image, options)

	if len(ret) == 0 {
		panic("no return value specified for ImageRemove")
	}

	var r0 client.ImageRemoveResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ImageRemoveOptions) (client.ImageRemoveResult, error)); ok {
		return returnFunc(ctx, image, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ImageRemoveOptions) client.ImageRemoveResult); ok {
		r0 = returnFunc(ctx, image, options)
	} else {
		r0 = ret.Get(0).(client.ImageRemoveResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ImageRemoveOptions) error); ok {
		r1 = returnFunc(ctx, image, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockClient_ImageRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageRemove'
type mockClient_ImageRemove_Call struct {
	*mock.Call
}

// ImageRemove is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
//   - options client.ImageRemoveOptions
func (_e *mockClient_Expecter) ImageRemove(ctx any, image any, options any) *mockClient_ImageRemove_Call {
	return &mockClient_ImageRemove_Call{Call: _e.mock.On("ImageRemove", ctx, image, options)}
}

func (_c *mockClient_ImageRemove_Call) Run(run func(ctx context.Context, image string, options client.ImageRemoveOptions)) *mockClient_ImageRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ImageRemoveOptions
		if args[2] != nil {
			arg2 = args[2].(client.ImageRemoveOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockClient_ImageRemove_Call) Return(imageRemoveResult client.ImageRemoveResult, err error) *mockClient_ImageRemove_Call {
	_c.Call.Return(imageRemoveResult, err)
	return _c
}

func (_c *mockClient_ImageRemove_Call) RunAndReturn(run func(ctx context.Context, image string, options client.ImageRemoveOptions) (client.ImageRemoveResult, error)) *mockClient_ImageRemove_Call {
	_c.Call.Return(run)
	return _c
}
