// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package backup

import (
	"context"
	"os"

	"github.com/pablovarela/media-server-engine/internal/restic"
	mock "github.com/stretchr/testify/mock"
)

// newMockRepository creates a new instance of mockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockRepository is an autogenerated mock type for the Repository type
type mockRepository struct {
	mock.Mock
}

type mockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRepository) EXPECT() *mockRepository_Expecter {
	return &mockRepository_Expecter{mock: &_m.Mock}
}

// Backup provides a mock function for the type mockRepository
func (_mock *mockRepository) Backup(ctx context.Context, options restic.BackupOptions) error {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Backup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, restic.BackupOptions) error); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockRepository_Backup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backup'
type mockRepository_Backup_Call struct {
	*mock.Call
}

// Backup is a helper method to define mock.On call
//   - ctx context.Context
//   - options restic.BackupOptions
func (_e *mockRepository_Expecter) Backup(ctx any, options any) *mockRepository_Backup_Call {
	return &mockRepository_Backup_Call{Call: _e.mock.On("Backup", ctx, options)}
}

func (_c *mockRepository_Backup_Call) Run(run func(ctx context.Context, options restic.BackupOptions)) *mockRepository_Backup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 restic.BackupOptions
		if args[1] != nil {
			arg1 = args[1].(restic.BackupOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockRepository_Backup_Call) Return(err error) *mockRepository_Backup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockRepository_Backup_Call) RunAndReturn(run func(ctx context.Context, options restic.BackupOptions) error) *mockRepository_Backup_Call {
	_c.Call.Return(run)
	return _c
}

// Check provides a mock function for the type mockRepository
func (_mock *mockRepository) Check(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockRepository_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type mockRepository_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockRepository_Expecter) Check(ctx any) *mockRepository_Check_Call {
	return &mockRepository_Check_Call{Call: _e.mock.On("Check", ctx)}
}

func (_c *mockRepository_Check_Call) Run(run func(ctx context.Context)) *mockRepository_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockRepository_Check_Call) Return(err error) *mockRepository_Check_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockRepository_Check_Call) RunAndReturn(run func(ctx context.Context) error) *mockRepository_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Forget provides a mock function for the type mockRepository
func (_mock *mockRepository) Forget(ctx context.Context, host string, inherit []*os.File) error {
	ret := _mock.Called(ctx, host, inherit)

	if len(ret) == 0 {
		panic("no return value specified for Forget")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*os.File) error); ok {
		r0 = returnFunc(ctx, host, inherit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockRepository_Forget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forget'
type mockRepository_Forget_Call struct {
	*mock.Call
}

// Forget is a helper method to define mock.On call
//   - ctx context.Context
//   - host string
//   - inherit []*os.File
func (_e *mockRepository_Expecter) Forget(ctx any, host any, inherit any) *mockRepository_Forget_Call {
	return &mockRepository_Forget_Call{Call: _e.mock.On("Forget", ctx, host, inherit)}
}

func (_c *mockRepository_Forget_Call) Run(run func(ctx context.Context, host string, inherit []*os.File)) *mockRepository_Forget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*os.File
		if args[2] != nil {
			arg2 = args[2].([]*os.File)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockRepository_Forget_Call) Return(err error) *mockRepository_Forget_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockRepository_Forget_Call) RunAndReturn(run func(ctx context.Context, host string, inherit []*os.File) error) *mockRepository_Forget_Call {
	_c.Call.Return(run)
	return _c
}

// HasRepository provides a mock function for the type mockRepository
func (_mock *mockRepository) HasRepository(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HasRepository")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockRepository_HasRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRepository'
type mockRepository_HasRepository_Call struct {
	*mock.Call
}

// HasRepository is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockRepository_Expecter) HasRepository(ctx any) *mockRepository_HasRepository_Call {
	return &mockRepository_HasRepository_Call{Call: _e.mock.On("HasRepository", ctx)}
}

func (_c *mockRepository_HasRepository_Call) Run(run func(ctx context.Context)) *mockRepository_HasRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockRepository_HasRepository_Call) Return(b bool, err error) *mockRepository_HasRepository_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockRepository_HasRepository_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *mockRepository_HasRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type mockRepository
func (_mock *mockRepository) Init(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockRepository_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type mockRepository_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockRepository_Expecter) Init(ctx any) *mockRepository_Init_Call {
	return &mockRepository_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *mockRepository_Init_Call) Run(run func(ctx context.Context)) *mockRepository_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockRepository_Init_Call) Return(err error) *mockRepository_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockRepository_Init_Call) RunAndReturn(run func(ctx context.Context) error) *mockRepository_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Locks provides a mock function for the type mockRepository
func (_mock *mockRepository) Locks(ctx context.Context) ([]restic.Lock, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Locks")
	}

	var r0 []restic.Lock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]restic.Lock, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []restic.Lock); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]restic.Lock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockRepository_Locks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Locks'
type mockRepository_Locks_Call struct {
	*mock.Call
}

// Locks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockRepository_Expecter) Locks(ctx any) *mockRepository_Locks_Call {
	return &mockRepository_Locks_Call{Call: _e.mock.On("Locks", ctx)}
}

func (_c *mockRepository_Locks_Call) Run(run func(ctx context.Context)) *mockRepository_Locks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockRepository_Locks_Call) Return(locks []restic.Lock, err error) *mockRepository_Locks_Call {
	_c.Call.Return(locks, err)
	return _c
}

func (_c *mockRepository_Locks_Call) RunAndReturn(run func(ctx context.Context) ([]restic.Lock, error)) *mockRepository_Locks_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type mockRepository
func (_mock *mockRepository) Restore(ctx context.Context, options restic.RestoreOptions) error {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, restic.RestoreOptions) error); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockRepository_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type mockRepository_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - options restic.RestoreOptions
func (_e *mockRepository_Expecter) Restore(ctx any, options any) *mockRepository_Restore_Call {
	return &mockRepository_Restore_Call{Call: _e.mock.On("Restore", ctx, options)}
}

func (_c *mockRepository_Restore_Call) Run(run func(ctx context.Context, options restic.RestoreOptions)) *mockRepository_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 restic.RestoreOptions
		if args[1] != nil {
			arg1 = args[1].(restic.RestoreOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockRepository_Restore_Call) Return(err error) *mockRepository_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockRepository_Restore_Call) RunAndReturn(run func(ctx context.Context, options restic.RestoreOptions) error) *mockRepository_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshots provides a mock function for the type mockRepository
func (_mock *mockRepository) Snapshots(ctx context.Context, host string) ([]restic.Snapshot, error) {
	ret := _mock.Called(ctx, host)

	if len(ret) == 0 {
		panic("no return value specified for Snapshots")
	}

	var r0 []restic.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]restic.Snapshot, error)); ok {
		return returnFunc(ctx, host)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []restic.Snapshot); ok {
		r0 = returnFunc(ctx, host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]restic.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, host)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockRepository_Snapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshots'
type mockRepository_Snapshots_Call struct {
	*mock.Call
}

// Snapshots is a helper method to define mock.On call
//   - ctx context.Context
//   - host string
func (_e *mockRepository_Expecter) Snapshots(ctx any, host any) *mockRepository_Snapshots_Call {
	return &mockRepository_Snapshots_Call{Call: _e.mock.On("Snapshots", ctx, host)}
}

func (_c *mockRepository_Snapshots_Call) Run(run func(ctx context.Context, host string)) *mockRepository_Snapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockRepository_Snapshots_Call) Return(snapshots []restic.Snapshot, err error) *mockRepository_Snapshots_Call {
	_c.Call.Return(snapshots, err)
	return _c
}

func (_c *mockRepository_Snapshots_Call) RunAndReturn(run func(ctx context.Context, host string) ([]restic.Snapshot, error)) *mockRepository_Snapshots_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function for the type mockRepository
func (_mock *mockRepository) Unlock(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockRepository_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type mockRepository_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockRepository_Expecter) Unlock(ctx any) *mockRepository_Unlock_Call {
	return &mockRepository_Unlock_Call{Call: _e.mock.On("Unlock", ctx)}
}

func (_c *mockRepository_Unlock_Call) Run(run func(ctx context.Context)) *mockRepository_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockRepository_Unlock_Call) Return(err error) *mockRepository_Unlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockRepository_Unlock_Call) RunAndReturn(run func(ctx context.Context) error) *mockRepository_Unlock_Call {
	_c.Call.Return(run)
	return _c
}

// UnlockAll provides a mock function for the type mockRepository
func (_mock *mockRepository) UnlockAll(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UnlockAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockRepository_UnlockAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlockAll'
type mockRepository_UnlockAll_Call struct {
	*mock.Call
}

// UnlockAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockRepository_Expecter) UnlockAll(ctx any) *mockRepository_UnlockAll_Call {
	return &mockRepository_UnlockAll_Call{Call: _e.mock.On("UnlockAll", ctx)}
}

func (_c *mockRepository_UnlockAll_Call) Run(run func(ctx context.Context)) *mockRepository_UnlockAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockRepository_UnlockAll_Call) Return(err error) *mockRepository_UnlockAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockRepository_UnlockAll_Call) RunAndReturn(run func(ctx context.Context) error) *mockRepository_UnlockAll_Call {
	_c.Call.Return(run)
	return _c
}

// newMockStack creates a new instance of mockStack. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStack(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStack {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockStack{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockStack is an autogenerated mock type for the Stack type
type mockStack struct {
	mock.Mock
}

type mockStack_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStack) EXPECT() *mockStack_Expecter {
	return &mockStack_Expecter{mock: &_m.Mock}
}

// AnyRunning provides a mock function for the type mockStack
func (_mock *mockStack) AnyRunning(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AnyRunning")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockStack_AnyRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnyRunning'
type mockStack_AnyRunning_Call struct {
	*mock.Call
}

// AnyRunning is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockStack_Expecter) AnyRunning(ctx any) *mockStack_AnyRunning_Call {
	return &mockStack_AnyRunning_Call{Call: _e.mock.On("AnyRunning", ctx)}
}

func (_c *mockStack_AnyRunning_Call) Run(run func(ctx context.Context)) *mockStack_AnyRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockStack_AnyRunning_Call) Return(b bool, err error) *mockStack_AnyRunning_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockStack_AnyRunning_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *mockStack_AnyRunning_Call {
	_c.Call.Return(run)
	return _c
}

// RunningServices provides a mock function for the type mockStack
func (_mock *mockStack) RunningServices(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunningServices")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockStack_RunningServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunningServices'
type mockStack_RunningServices_Call struct {
	*mock.Call
}

// RunningServices is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockStack_Expecter) RunningServices(ctx any) *mockStack_RunningServices_Call {
	return &mockStack_RunningServices_Call{Call: _e.mock.On("RunningServices", ctx)}
}

func (_c *mockStack_RunningServices_Call) Run(run func(ctx context.Context)) *mockStack_RunningServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockStack_RunningServices_Call) Return(strings []string, err error) *mockStack_RunningServices_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *mockStack_RunningServices_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *mockStack_RunningServices_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type mockStack
func (_mock *mockStack) Start(ctx context.Context, services []string) error {
	ret := _mock.Called(ctx, services)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, services)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStack_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mockStack_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - services []string
func (_e *mockStack_Expecter) Start(ctx any, services any) *mockStack_Start_Call {
	return &mockStack_Start_Call{Call: _e.mock.On("Start", ctx, services)}
}

func (_c *mockStack_Start_Call) Run(run func(ctx context.Context, services []string)) *mockStack_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockStack_Start_Call) Return(err error) *mockStack_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStack_Start_Call) RunAndReturn(run func(ctx context.Context, services []string) error) *mockStack_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type mockStack
func (_mock *mockStack) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStack_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type mockStack_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockStack_Expecter) Stop(ctx any) *mockStack_Stop_Call {
	return &mockStack_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *mockStack_Stop_Call) Run(run func(ctx context.Context)) *mockStack_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockStack_Stop_Call) Return(err error) *mockStack_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStack_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *mockStack_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPinger creates a new instance of mockPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPinger {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockPinger is an autogenerated mock type for the Pinger type
type mockPinger struct {
	mock.Mock
}

type mockPinger_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPinger) EXPECT() *mockPinger_Expecter {
	return &mockPinger_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type mockPinger
func (_mock *mockPinger) Ping(ctx context.Context, job string, suffix string) {
	_mock.Called(ctx, job, suffix)
	return
}

// mockPinger_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type mockPinger_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - job string
//   - suffix string
func (_e *mockPinger_Expecter) Ping(ctx any, job any, suffix any) *mockPinger_Ping_Call {
	return &mockPinger_Ping_Call{Call: _e.mock.On("Ping", ctx, job, suffix)}
}

func (_c *mockPinger_Ping_Call) Run(run func(ctx context.Context, job string, suffix string)) *mockPinger_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockPinger_Ping_Call) Return() *mockPinger_Ping_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockPinger_Ping_Call) RunAndReturn(run func(ctx context.Context, job string, suffix string)) *mockPinger_Ping_Call {
	_c.Run(run)
	return _c
}
