// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cmd

import (
	"context"
	"io"

	"github.com/compose-spec/compose-go/v2/types"
	"github.com/pablovarela/media-server-engine/internal/compose"
	"github.com/pablovarela/media-server-engine/internal/configure"
	"github.com/pablovarela/media-server-engine/internal/installation"
	"github.com/pablovarela/media-server-engine/internal/process"
	"github.com/pablovarela/media-server-engine/internal/selfupdate"
	"github.com/pablovarela/media-server-engine/internal/version"
	mock "github.com/stretchr/testify/mock"
)

// newMockCommandRunner creates a new instance of mockCommandRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCommandRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCommandRunner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockCommandRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockCommandRunner is an autogenerated mock type for the commandRunner type
type mockCommandRunner struct {
	mock.Mock
}

type mockCommandRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCommandRunner) EXPECT() *mockCommandRunner_Expecter {
	return &mockCommandRunner_Expecter{mock: &_m.Mock}
}

// Output provides a mock function for the type mockCommandRunner
func (_mock *mockCommandRunner) Output(ctx context.Context, c process.Command) (process.Result, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 process.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, process.Command) (process.Result, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, process.Command) process.Result); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Get(0).(process.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, process.Command) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockCommandRunner_Output_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Output'
type mockCommandRunner_Output_Call struct {
	*mock.Call
}

// Output is a helper method to define mock.On call
//   - ctx context.Context
//   - c process.Command
func (_e *mockCommandRunner_Expecter) Output(ctx any, c any) *mockCommandRunner_Output_Call {
	return &mockCommandRunner_Output_Call{Call: _e.mock.On("Output", ctx, c)}
}

func (_c *mockCommandRunner_Output_Call) Run(run func(ctx context.Context, c process.Command)) *mockCommandRunner_Output_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 process.Command
		if args[1] != nil {
			arg1 = args[1].(process.Command)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockCommandRunner_Output_Call) Return(result process.Result, err error) *mockCommandRunner_Output_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockCommandRunner_Output_Call) RunAndReturn(run func(ctx context.Context, c process.Command) (process.Result, error)) *mockCommandRunner_Output_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type mockCommandRunner
func (_mock *mockCommandRunner) Run(ctx context.Context, c process.Command) (int, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, process.Command) (int, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, process.Command) int); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, process.Command) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockCommandRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockCommandRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - c process.Command
func (_e *mockCommandRunner_Expecter) Run(ctx any, c any) *mockCommandRunner_Run_Call {
	return &mockCommandRunner_Run_Call{Call: _e.mock.On("Run", ctx, c)}
}

func (_c *mockCommandRunner_Run_Call) Run(run func(ctx context.Context, c process.Command)) *mockCommandRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 process.Command
		if args[1] != nil {
			arg1 = args[1].(process.Command)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockCommandRunner_Run_Call) Return(n int, err error) *mockCommandRunner_Run_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockCommandRunner_Run_Call) RunAndReturn(run func(ctx context.Context, c process.Command) (int, error)) *mockCommandRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPrompter creates a new instance of mockPrompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPrompter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockPrompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockPrompter is an autogenerated mock type for the prompter type
type mockPrompter struct {
	mock.Mock
}

type mockPrompter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPrompter) EXPECT() *mockPrompter_Expecter {
	return &mockPrompter_Expecter{mock: &_m.Mock}
}

// Acknowledge provides a mock function for the type mockPrompter
func (_mock *mockPrompter) Acknowledge(title string, text string, word string) error {
	ret := _mock.Called(title, text, word)

	if len(ret) == 0 {
		panic("no return value specified for Acknowledge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(title, text, word)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPrompter_Acknowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acknowledge'
type mockPrompter_Acknowledge_Call struct {
	*mock.Call
}

// Acknowledge is a helper method to define mock.On call
//   - title string
//   - text string
//   - word string
func (_e *mockPrompter_Expecter) Acknowledge(title any, text any, word any) *mockPrompter_Acknowledge_Call {
	return &mockPrompter_Acknowledge_Call{Call: _e.mock.On("Acknowledge", title, text, word)}
}

func (_c *mockPrompter_Acknowledge_Call) Run(run func(title string, text string, word string)) *mockPrompter_Acknowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockPrompter_Acknowledge_Call) Return(err error) *mockPrompter_Acknowledge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPrompter_Acknowledge_Call) RunAndReturn(run func(title string, text string, word string) error) *mockPrompter_Acknowledge_Call {
	_c.Call.Return(run)
	return _c
}

// Ask provides a mock function for the type mockPrompter
func (_mock *mockPrompter) Ask(question string, yes bool) (bool, error) {
	ret := _mock.Called(question, yes)

	if len(ret) == 0 {
		panic("no return value specified for Ask")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) (bool, error)); ok {
		return returnFunc(question, yes)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool) bool); ok {
		r0 = returnFunc(question, yes)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = returnFunc(question, yes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPrompter_Ask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ask'
type mockPrompter_Ask_Call struct {
	*mock.Call
}

// Ask is a helper method to define mock.On call
//   - question string
//   - yes bool
func (_e *mockPrompter_Expecter) Ask(question any, yes any) *mockPrompter_Ask_Call {
	return &mockPrompter_Ask_Call{Call: _e.mock.On("Ask", question, yes)}
}

func (_c *mockPrompter_Ask_Call) Run(run func(question string, yes bool)) *mockPrompter_Ask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPrompter_Ask_Call) Return(b bool, err error) *mockPrompter_Ask_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockPrompter_Ask_Call) RunAndReturn(run func(question string, yes bool) (bool, error)) *mockPrompter_Ask_Call {
	_c.Call.Return(run)
	return _c
}

// Confirm provides a mock function for the type mockPrompter
func (_mock *mockPrompter) Confirm(question string, lines []string) (bool, error) {
	ret := _mock.Called(question, lines)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []string) (bool, error)); ok {
		return returnFunc(question, lines)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string) bool); ok {
		r0 = returnFunc(question, lines)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = returnFunc(question, lines)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPrompter_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type mockPrompter_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - question string
//   - lines []string
func (_e *mockPrompter_Expecter) Confirm(question any, lines any) *mockPrompter_Confirm_Call {
	return &mockPrompter_Confirm_Call{Call: _e.mock.On("Confirm", question, lines)}
}

func (_c *mockPrompter_Confirm_Call) Run(run func(question string, lines []string)) *mockPrompter_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPrompter_Confirm_Call) Return(b bool, err error) *mockPrompter_Confirm_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockPrompter_Confirm_Call) RunAndReturn(run func(question string, lines []string) (bool, error)) *mockPrompter_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// Menu provides a mock function for the type mockPrompter
func (_mock *mockPrompter) Menu(title string, items []configure.MenuItem) (string, error) {
	ret := _mock.Called(title, items)

	if len(ret) == 0 {
		panic("no return value specified for Menu")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []configure.MenuItem) (string, error)); ok {
		return returnFunc(title, items)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []configure.MenuItem) string); ok {
		r0 = returnFunc(title, items)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []configure.MenuItem) error); ok {
		r1 = returnFunc(title, items)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPrompter_Menu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Menu'
type mockPrompter_Menu_Call struct {
	*mock.Call
}

// Menu is a helper method to define mock.On call
//   - title string
//   - items []configure.MenuItem
func (_e *mockPrompter_Expecter) Menu(title any, items any) *mockPrompter_Menu_Call {
	return &mockPrompter_Menu_Call{Call: _e.mock.On("Menu", title, items)}
}

func (_c *mockPrompter_Menu_Call) Run(run func(title string, items []configure.MenuItem)) *mockPrompter_Menu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []configure.MenuItem
		if args[1] != nil {
			arg1 = args[1].([]configure.MenuItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPrompter_Menu_Call) Return(s string, err error) *mockPrompter_Menu_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockPrompter_Menu_Call) RunAndReturn(run func(title string, items []configure.MenuItem) (string, error)) *mockPrompter_Menu_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function for the type mockPrompter
func (_mock *mockPrompter) Rotate(apps []configure.App) ([]configure.App, error) {
	ret := _mock.Called(apps)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 []configure.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]configure.App) ([]configure.App, error)); ok {
		return returnFunc(apps)
	}
	if returnFunc, ok := ret.Get(0).(func([]configure.App) []configure.App); ok {
		r0 = returnFunc(apps)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]configure.App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]configure.App) error); ok {
		r1 = returnFunc(apps)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPrompter_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type mockPrompter_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - apps []configure.App
func (_e *mockPrompter_Expecter) Rotate(apps any) *mockPrompter_Rotate_Call {
	return &mockPrompter_Rotate_Call{Call: _e.mock.On("Rotate", apps)}
}

func (_c *mockPrompter_Rotate_Call) Run(run func(apps []configure.App)) *mockPrompter_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []configure.App
		if args[0] != nil {
			arg0 = args[0].([]configure.App)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockPrompter_Rotate_Call) Return(apps1 []configure.App, err error) *mockPrompter_Rotate_Call {
	_c.Call.Return(apps1, err)
	return _c
}

func (_c *mockPrompter_Rotate_Call) RunAndReturn(run func(apps []configure.App) ([]configure.App, error)) *mockPrompter_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// Secret provides a mock function for the type mockPrompter
func (_mock *mockPrompter) Secret(title string, description string, validate func(string) error) (string, error) {
	ret := _mock.Called(title, description, validate)

	if len(ret) == 0 {
		panic("no return value specified for Secret")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, func(string) error) (string, error)); ok {
		return returnFunc(title, description, validate)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, func(string) error) string); ok {
		r0 = returnFunc(title, description, validate)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, func(string) error) error); ok {
		r1 = returnFunc(title, description, validate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPrompter_Secret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Secret'
type mockPrompter_Secret_Call struct {
	*mock.Call
}

// Secret is a helper method to define mock.On call
//   - title string
//   - description string
//   - validate func(string) error
func (_e *mockPrompter_Expecter) Secret(title any, description any, validate any) *mockPrompter_Secret_Call {
	return &mockPrompter_Secret_Call{Call: _e.mock.On("Secret", title, description, validate)}
}

func (_c *mockPrompter_Secret_Call) Run(run func(title string, description string, validate func(string) error)) *mockPrompter_Secret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 func(string) error
		if args[2] != nil {
			arg2 = args[2].(func(string) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockPrompter_Secret_Call) Return(s string, err error) *mockPrompter_Secret_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockPrompter_Secret_Call) RunAndReturn(run func(title string, description string, validate func(string) error) (string, error)) *mockPrompter_Secret_Call {
	_c.Call.Return(run)
	return _c
}

// Section provides a mock function for the type mockPrompter
func (_mock *mockPrompter) Section(title string, fields []configure.Field, form configure.Form) (map[string]string, error) {
	ret := _mock.Called(title, fields, form)

	if len(ret) == 0 {
		panic("no return value specified for Section")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []configure.Field, configure.Form) (map[string]string, error)); ok {
		return returnFunc(title, fields, form)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []configure.Field, configure.Form) map[string]string); ok {
		r0 = returnFunc(title, fields, form)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []configure.Field, configure.Form) error); ok {
		r1 = returnFunc(title, fields, form)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPrompter_Section_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Section'
type mockPrompter_Section_Call struct {
	*mock.Call
}

// Section is a helper method to define mock.On call
//   - title string
//   - fields []configure.Field
//   - form configure.Form
func (_e *mockPrompter_Expecter) Section(title any, fields any, form any) *mockPrompter_Section_Call {
	return &mockPrompter_Section_Call{Call: _e.mock.On("Section", title, fields, form)}
}

func (_c *mockPrompter_Section_Call) Run(run func(title string, fields []configure.Field, form configure.Form)) *mockPrompter_Section_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []configure.Field
		if args[1] != nil {
			arg1 = args[1].([]configure.Field)
		}
		var arg2 configure.Form
		if args[2] != nil {
			arg2 = args[2].(configure.Form)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockPrompter_Section_Call) Return(stringToString map[string]string, err error) *mockPrompter_Section_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *mockPrompter_Section_Call) RunAndReturn(run func(title string, fields []configure.Field, form configure.Form) (map[string]string, error)) *mockPrompter_Section_Call {
	_c.Call.Return(run)
	return _c
}

// newMockConfigRepositories creates a new instance of mockConfigRepositories. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConfigRepositories(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConfigRepositories {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockConfigRepositories{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockConfigRepositories is an autogenerated mock type for the configRepositories type
type mockConfigRepositories struct {
	mock.Mock
}

type mockConfigRepositories_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConfigRepositories) EXPECT() *mockConfigRepositories_Expecter {
	return &mockConfigRepositories_Expecter{mock: &_m.Mock}
}

// CreatePrivateRepository provides a mock function for the type mockConfigRepositories
func (_mock *mockConfigRepositories) CreatePrivateRepository(ctx context.Context, org string, repo string) (string, error) {
	ret := _mock.Called(ctx, org, repo)

	if len(ret) == 0 {
		panic("no return value specified for CreatePrivateRepository")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, org, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, org, repo)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, org, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConfigRepositories_CreatePrivateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePrivateRepository'
type mockConfigRepositories_CreatePrivateRepository_Call struct {
	*mock.Call
}

// CreatePrivateRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - org string
//   - repo string
func (_e *mockConfigRepositories_Expecter) CreatePrivateRepository(ctx any, org any, repo any) *mockConfigRepositories_CreatePrivateRepository_Call {
	return &mockConfigRepositories_CreatePrivateRepository_Call{Call: _e.mock.On("CreatePrivateRepository", ctx, org, repo)}
}

func (_c *mockConfigRepositories_CreatePrivateRepository_Call) Run(run func(ctx context.Context, org string, repo string)) *mockConfigRepositories_CreatePrivateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockConfigRepositories_CreatePrivateRepository_Call) Return(s string, err error) *mockConfigRepositories_CreatePrivateRepository_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockConfigRepositories_CreatePrivateRepository_Call) RunAndReturn(run func(ctx context.Context, org string, repo string) (string, error)) *mockConfigRepositories_CreatePrivateRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type mockConfigRepositories
func (_mock *mockConfigRepositories) Login(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConfigRepositories_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type mockConfigRepositories_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockConfigRepositories_Expecter) Login(ctx any) *mockConfigRepositories_Login_Call {
	return &mockConfigRepositories_Login_Call{Call: _e.mock.On("Login", ctx)}
}

func (_c *mockConfigRepositories_Login_Call) Run(run func(ctx context.Context)) *mockConfigRepositories_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConfigRepositories_Login_Call) Return(s string, err error) *mockConfigRepositories_Login_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockConfigRepositories_Login_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *mockConfigRepositories_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RepositoryExists provides a mock function for the type mockConfigRepositories
func (_mock *mockConfigRepositories) RepositoryExists(ctx context.Context, owner string, repo string) (bool, error) {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for RepositoryExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, owner, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConfigRepositories_RepositoryExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepositoryExists'
type mockConfigRepositories_RepositoryExists_Call struct {
	*mock.Call
}

// RepositoryExists is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *mockConfigRepositories_Expecter) RepositoryExists(ctx any, owner any, repo any) *mockConfigRepositories_RepositoryExists_Call {
	return &mockConfigRepositories_RepositoryExists_Call{Call: _e.mock.On("RepositoryExists", ctx, owner, repo)}
}

func (_c *mockConfigRepositories_RepositoryExists_Call) Run(run func(ctx context.Context, owner string, repo string)) *mockConfigRepositories_RepositoryExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockConfigRepositories_RepositoryExists_Call) Return(b bool, err error) *mockConfigRepositories_RepositoryExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockConfigRepositories_RepositoryExists_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) (bool, error)) *mockConfigRepositories_RepositoryExists_Call {
	_c.Call.Return(run)
	return _c
}

// newMockComposeRunner creates a new instance of mockComposeRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockComposeRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockComposeRunner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockComposeRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockComposeRunner is an autogenerated mock type for the composeRunner type
type mockComposeRunner struct {
	mock.Mock
}

type mockComposeRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockComposeRunner) EXPECT() *mockComposeRunner_Expecter {
	return &mockComposeRunner_Expecter{mock: &_m.Mock}
}

// AnyRunning provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) AnyRunning(ctx context.Context, project *types.Project) (bool, error) {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for AnyRunning")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) (bool, error)); ok {
		return returnFunc(ctx, project)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) bool); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Project) error); ok {
		r1 = returnFunc(ctx, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockComposeRunner_AnyRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnyRunning'
type mockComposeRunner_AnyRunning_Call struct {
	*mock.Call
}

// AnyRunning is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
func (_e *mockComposeRunner_Expecter) AnyRunning(ctx any, project any) *mockComposeRunner_AnyRunning_Call {
	return &mockComposeRunner_AnyRunning_Call{Call: _e.mock.On("AnyRunning", ctx, project)}
}

func (_c *mockComposeRunner_AnyRunning_Call) Run(run func(ctx context.Context, project *types.Project)) *mockComposeRunner_AnyRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockComposeRunner_AnyRunning_Call) Return(b bool, err error) *mockComposeRunner_AnyRunning_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockComposeRunner_AnyRunning_Call) RunAndReturn(run func(ctx context.Context, project *types.Project) (bool, error)) *mockComposeRunner_AnyRunning_Call {
	_c.Call.Return(run)
	return _c
}

// Containers provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Containers(ctx context.Context, projectName string) ([]compose.Container, error) {
	ret := _mock.Called(ctx, projectName)

	if len(ret) == 0 {
		panic("no return value specified for Containers")
	}

	var r0 []compose.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]compose.Container, error)); ok {
		return returnFunc(ctx, projectName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []compose.Container); ok {
		r0 = returnFunc(ctx, projectName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compose.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, projectName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockComposeRunner_Containers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Containers'
type mockComposeRunner_Containers_Call struct {
	*mock.Call
}

// Containers is a helper method to define mock.On call
//   - ctx context.Context
//   - projectName string
func (_e *mockComposeRunner_Expecter) Containers(ctx any, projectName any) *mockComposeRunner_Containers_Call {
	return &mockComposeRunner_Containers_Call{Call: _e.mock.On("Containers", ctx, projectName)}
}

func (_c *mockComposeRunner_Containers_Call) Run(run func(ctx context.Context, projectName string)) *mockComposeRunner_Containers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Containers_Call) Return(containers []compose.Container, err error) *mockComposeRunner_Containers_Call {
	_c.Call.Return(containers, err)
	return _c
}

func (_c *mockComposeRunner_Containers_Call) RunAndReturn(run func(ctx context.Context, projectName string) ([]compose.Container, error)) *mockComposeRunner_Containers_Call {
	_c.Call.Return(run)
	return _c
}

// Detached provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Detached(ctx context.Context, project *types.Project, from string, dependents []string) ([]string, error) {
	ret := _mock.Called(ctx, project, from, dependents)

	if len(ret) == 0 {
		panic("no return value specified for Detached")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, string, []string) ([]string, error)); ok {
		return returnFunc(ctx, project, from, dependents)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, string, []string) []string); ok {
		r0 = returnFunc(ctx, project, from, dependents)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Project, string, []string) error); ok {
		r1 = returnFunc(ctx, project, from, dependents)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockComposeRunner_Detached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detached'
type mockComposeRunner_Detached_Call struct {
	*mock.Call
}

// Detached is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - from string
//   - dependents []string
func (_e *mockComposeRunner_Expecter) Detached(ctx any, project any, from any, dependents any) *mockComposeRunner_Detached_Call {
	return &mockComposeRunner_Detached_Call{Call: _e.mock.On("Detached", ctx, project, from, dependents)}
}

func (_c *mockComposeRunner_Detached_Call) Run(run func(ctx context.Context, project *types.Project, from string, dependents []string)) *mockComposeRunner_Detached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Detached_Call) Return(strings []string, err error) *mockComposeRunner_Detached_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *mockComposeRunner_Detached_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, from string, dependents []string) ([]string, error)) *mockComposeRunner_Detached_Call {
	_c.Call.Return(run)
	return _c
}

// Down provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Down(ctx context.Context, project *types.Project) error {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Down")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) error); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Down_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Down'
type mockComposeRunner_Down_Call struct {
	*mock.Call
}

// Down is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
func (_e *mockComposeRunner_Expecter) Down(ctx any, project any) *mockComposeRunner_Down_Call {
	return &mockComposeRunner_Down_Call{Call: _e.mock.On("Down", ctx, project)}
}

func (_c *mockComposeRunner_Down_Call) Run(run func(ctx context.Context, project *types.Project)) *mockComposeRunner_Down_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Down_Call) Return(err error) *mockComposeRunner_Down_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Down_Call) RunAndReturn(run func(ctx context.Context, project *types.Project) error) *mockComposeRunner_Down_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Load(ctx context.Context, i *installation.Installation, kind compose.Kind, variables []string, profiles []string) (*types.Project, error) {
	ret := _mock.Called(ctx, i, kind, variables, profiles)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *types.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *installation.Installation, compose.Kind, []string, []string) (*types.Project, error)); ok {
		return returnFunc(ctx, i, kind, variables, profiles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *installation.Installation, compose.Kind, []string, []string) *types.Project); ok {
		r0 = returnFunc(ctx, i, kind, variables, profiles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *installation.Installation, compose.Kind, []string, []string) error); ok {
		r1 = returnFunc(ctx, i, kind, variables, profiles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockComposeRunner_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type mockComposeRunner_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - i *installation.Installation
//   - kind compose.Kind
//   - variables []string
//   - profiles []string
func (_e *mockComposeRunner_Expecter) Load(ctx any, i any, kind any, variables any, profiles any) *mockComposeRunner_Load_Call {
	return &mockComposeRunner_Load_Call{Call: _e.mock.On("Load", ctx, i, kind, variables, profiles)}
}

func (_c *mockComposeRunner_Load_Call) Run(run func(ctx context.Context, i *installation.Installation, kind compose.Kind, variables []string, profiles []string)) *mockComposeRunner_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *installation.Installation
		if args[1] != nil {
			arg1 = args[1].(*installation.Installation)
		}
		var arg2 compose.Kind
		if args[2] != nil {
			arg2 = args[2].(compose.Kind)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Load_Call) Return(project *types.Project, err error) *mockComposeRunner_Load_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *mockComposeRunner_Load_Call) RunAndReturn(run func(ctx context.Context, i *installation.Installation, kind compose.Kind, variables []string, profiles []string) (*types.Project, error)) *mockComposeRunner_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Logs provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Logs(ctx context.Context, project *types.Project, options compose.LogsOptions, w io.Writer) error {
	ret := _mock.Called(ctx, project, options, w)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, compose.LogsOptions, io.Writer) error); ok {
		r0 = returnFunc(ctx, project, options, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type mockComposeRunner_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - options compose.LogsOptions
//   - w io.Writer
func (_e *mockComposeRunner_Expecter) Logs(ctx any, project any, options any, w any) *mockComposeRunner_Logs_Call {
	return &mockComposeRunner_Logs_Call{Call: _e.mock.On("Logs", ctx, project, options, w)}
}

func (_c *mockComposeRunner_Logs_Call) Run(run func(ctx context.Context, project *types.Project, options compose.LogsOptions, w io.Writer)) *mockComposeRunner_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 compose.LogsOptions
		if args[2] != nil {
			arg2 = args[2].(compose.LogsOptions)
		}
		var arg3 io.Writer
		if args[3] != nil {
			arg3 = args[3].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Logs_Call) Return(err error) *mockComposeRunner_Logs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Logs_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, options compose.LogsOptions, w io.Writer) error) *mockComposeRunner_Logs_Call {
	_c.Call.Return(run)
	return _c
}

// Ps provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Ps(ctx context.Context, project *types.Project) ([]compose.Container, error) {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Ps")
	}

	var r0 []compose.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) ([]compose.Container, error)); ok {
		return returnFunc(ctx, project)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) []compose.Container); ok {
		r0 = returnFunc(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compose.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Project) error); ok {
		r1 = returnFunc(ctx, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockComposeRunner_Ps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ps'
type mockComposeRunner_Ps_Call struct {
	*mock.Call
}

// Ps is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
func (_e *mockComposeRunner_Expecter) Ps(ctx any, project any) *mockComposeRunner_Ps_Call {
	return &mockComposeRunner_Ps_Call{Call: _e.mock.On("Ps", ctx, project)}
}

func (_c *mockComposeRunner_Ps_Call) Run(run func(ctx context.Context, project *types.Project)) *mockComposeRunner_Ps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Ps_Call) Return(containers []compose.Container, err error) *mockComposeRunner_Ps_Call {
	_c.Call.Return(containers, err)
	return _c
}

func (_c *mockComposeRunner_Ps_Call) RunAndReturn(run func(ctx context.Context, project *types.Project) ([]compose.Container, error)) *mockComposeRunner_Ps_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Pull(ctx context.Context, project *types.Project) (compose.Pulled, error) {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 compose.Pulled
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) (compose.Pulled, error)); ok {
		return returnFunc(ctx, project)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) compose.Pulled); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Get(0).(compose.Pulled)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Project) error); ok {
		r1 = returnFunc(ctx, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockComposeRunner_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type mockComposeRunner_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
func (_e *mockComposeRunner_Expecter) Pull(ctx any, project any) *mockComposeRunner_Pull_Call {
	return &mockComposeRunner_Pull_Call{Call: _e.mock.On("Pull", ctx, project)}
}

func (_c *mockComposeRunner_Pull_Call) Run(run func(ctx context.Context, project *types.Project)) *mockComposeRunner_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Pull_Call) Return(pulled compose.Pulled, err error) *mockComposeRunner_Pull_Call {
	_c.Call.Return(pulled, err)
	return _c
}

func (_c *mockComposeRunner_Pull_Call) RunAndReturn(run func(ctx context.Context, project *types.Project) (compose.Pulled, error)) *mockComposeRunner_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Recreate provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Recreate(ctx context.Context, project *types.Project, services []string) error {
	ret := _mock.Called(ctx, project, services)

	if len(ret) == 0 {
		panic("no return value specified for Recreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, []string) error); ok {
		r0 = returnFunc(ctx, project, services)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Recreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recreate'
type mockComposeRunner_Recreate_Call struct {
	*mock.Call
}

// Recreate is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - services []string
func (_e *mockComposeRunner_Expecter) Recreate(ctx any, project any, services any) *mockComposeRunner_Recreate_Call {
	return &mockComposeRunner_Recreate_Call{Call: _e.mock.On("Recreate", ctx, project, services)}
}

func (_c *mockComposeRunner_Recreate_Call) Run(run func(ctx context.Context, project *types.Project, services []string)) *mockComposeRunner_Recreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Recreate_Call) Return(err error) *mockComposeRunner_Recreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Recreate_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, services []string) error) *mockComposeRunner_Recreate_Call {
	_c.Call.Return(run)
	return _c
}

// Restart provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Restart(ctx context.Context, project *types.Project, services []string) error {
	ret := _mock.Called(ctx, project, services)

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, []string) error); ok {
		r0 = returnFunc(ctx, project, services)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type mockComposeRunner_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - services []string
func (_e *mockComposeRunner_Expecter) Restart(ctx any, project any, services any) *mockComposeRunner_Restart_Call {
	return &mockComposeRunner_Restart_Call{Call: _e.mock.On("Restart", ctx, project, services)}
}

func (_c *mockComposeRunner_Restart_Call) Run(run func(ctx context.Context, project *types.Project, services []string)) *mockComposeRunner_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Restart_Call) Return(err error) *mockComposeRunner_Restart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Restart_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, services []string) error) *mockComposeRunner_Restart_Call {
	_c.Call.Return(run)
	return _c
}

// RunOnce provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) RunOnce(ctx context.Context, project *types.Project, service string, out io.Writer) (int, error) {
	ret := _mock.Called(ctx, project, service, out)

	if len(ret) == 0 {
		panic("no return value specified for RunOnce")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, string, io.Writer) (int, error)); ok {
		return returnFunc(ctx, project, service, out)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, string, io.Writer) int); ok {
		r0 = returnFunc(ctx, project, service, out)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Project, string, io.Writer) error); ok {
		r1 = returnFunc(ctx, project, service, out)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockComposeRunner_RunOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunOnce'
type mockComposeRunner_RunOnce_Call struct {
	*mock.Call
}

// RunOnce is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - service string
//   - out io.Writer
func (_e *mockComposeRunner_Expecter) RunOnce(ctx any, project any, service any, out any) *mockComposeRunner_RunOnce_Call {
	return &mockComposeRunner_RunOnce_Call{Call: _e.mock.On("RunOnce", ctx, project, service, out)}
}

func (_c *mockComposeRunner_RunOnce_Call) Run(run func(ctx context.Context, project *types.Project, service string, out io.Writer)) *mockComposeRunner_RunOnce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Writer
		if args[3] != nil {
			arg3 = args[3].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockComposeRunner_RunOnce_Call) Return(n int, err error) *mockComposeRunner_RunOnce_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockComposeRunner_RunOnce_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, service string, out io.Writer) (int, error)) *mockComposeRunner_RunOnce_Call {
	_c.Call.Return(run)
	return _c
}

// RunningServices provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) RunningServices(ctx context.Context, project *types.Project) ([]string, error) {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for RunningServices")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) ([]string, error)); ok {
		return returnFunc(ctx, project)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) []string); ok {
		r0 = returnFunc(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Project) error); ok {
		r1 = returnFunc(ctx, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockComposeRunner_RunningServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunningServices'
type mockComposeRunner_RunningServices_Call struct {
	*mock.Call
}

// RunningServices is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
func (_e *mockComposeRunner_Expecter) RunningServices(ctx any, project any) *mockComposeRunner_RunningServices_Call {
	return &mockComposeRunner_RunningServices_Call{Call: _e.mock.On("RunningServices", ctx, project)}
}

func (_c *mockComposeRunner_RunningServices_Call) Run(run func(ctx context.Context, project *types.Project)) *mockComposeRunner_RunningServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockComposeRunner_RunningServices_Call) Return(strings []string, err error) *mockComposeRunner_RunningServices_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *mockComposeRunner_RunningServices_Call) RunAndReturn(run func(ctx context.Context, project *types.Project) ([]string, error)) *mockComposeRunner_RunningServices_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Start(ctx context.Context, project *types.Project, services []string) error {
	ret := _mock.Called(ctx, project, services)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, []string) error); ok {
		r0 = returnFunc(ctx, project, services)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mockComposeRunner_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - services []string
func (_e *mockComposeRunner_Expecter) Start(ctx any, project any, services any) *mockComposeRunner_Start_Call {
	return &mockComposeRunner_Start_Call{Call: _e.mock.On("Start", ctx, project, services)}
}

func (_c *mockComposeRunner_Start_Call) Run(run func(ctx context.Context, project *types.Project, services []string)) *mockComposeRunner_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Start_Call) Return(err error) *mockComposeRunner_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Start_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, services []string) error) *mockComposeRunner_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Stop(ctx context.Context, project *types.Project) error {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) error); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type mockComposeRunner_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
func (_e *mockComposeRunner_Expecter) Stop(ctx any, project any) *mockComposeRunner_Stop_Call {
	return &mockComposeRunner_Stop_Call{Call: _e.mock.On("Stop", ctx, project)}
}

func (_c *mockComposeRunner_Stop_Call) Run(run func(ctx context.Context, project *types.Project)) *mockComposeRunner_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Stop_Call) Return(err error) *mockComposeRunner_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Stop_Call) RunAndReturn(run func(ctx context.Context, project *types.Project) error) *mockComposeRunner_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Up(ctx context.Context, project *types.Project, services []string, wait compose.Wait) error {
	ret := _mock.Called(ctx, project, services, wait)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, []string, compose.Wait) error); ok {
		r0 = returnFunc(ctx, project, services, wait)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type mockComposeRunner_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - services []string
//   - wait compose.Wait
func (_e *mockComposeRunner_Expecter) Up(ctx any, project any, services any, wait any) *mockComposeRunner_Up_Call {
	return &mockComposeRunner_Up_Call{Call: _e.mock.On("Up", ctx, project, services, wait)}
}

func (_c *mockComposeRunner_Up_Call) Run(run func(ctx context.Context, project *types.Project, services []string, wait compose.Wait)) *mockComposeRunner_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 compose.Wait
		if args[3] != nil {
			arg3 = args[3].(compose.Wait)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Up_Call) Return(err error) *mockComposeRunner_Up_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Up_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, services []string, wait compose.Wait) error) *mockComposeRunner_Up_Call {
	_c.Call.Return(run)
	return _c
}

// newMockUpdater creates a new instance of mockUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUpdater {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockUpdater is an autogenerated mock type for the updater type
type mockUpdater struct {
	mock.Mock
}

type mockUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUpdater) EXPECT() *mockUpdater_Expecter {
	return &mockUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function for the type mockUpdater
func (_mock *mockUpdater) Update(ctx context.Context, current version.Build, force bool, progress selfupdate.Progress) (selfupdate.Result, error) {
	ret := _mock.Called(ctx, current, force, progress)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 selfupdate.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, version.Build, bool, selfupdate.Progress) (selfupdate.Result, error)); ok {
		return returnFunc(ctx, current, force, progress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, version.Build, bool, selfupdate.Progress) selfupdate.Result); ok {
		r0 = returnFunc(ctx, current, force, progress)
	} else {
		r0 = ret.Get(0).(selfupdate.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, version.Build, bool, selfupdate.Progress) error); ok {
		r1 = returnFunc(ctx, current, force, progress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - current version.Build
//   - force bool
//   - progress selfupdate.Progress
func (_e *mockUpdater_Expecter) Update(ctx any, current any, force any, progress any) *mockUpdater_Update_Call {
	return &mockUpdater_Update_Call{Call: _e.mock.On("Update", ctx, current, force, progress)}
}

func (_c *mockUpdater_Update_Call) Run(run func(ctx context.Context, current version.Build, force bool, progress selfupdate.Progress)) *mockUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 version.Build
		if args[1] != nil {
			arg1 = args[1].(version.Build)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 selfupdate.Progress
		if args[3] != nil {
			arg3 = args[3].(selfupdate.Progress)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockUpdater_Update_Call) Return(result selfupdate.Result, err error) *mockUpdater_Update_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockUpdater_Update_Call) RunAndReturn(run func(ctx context.Context, current version.Build, force bool, progress selfupdate.Progress) (selfupdate.Result, error)) *mockUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}
