// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cmd

import (
	"context"
	"io"

	"github.com/compose-spec/compose-go/v2/types"
	"github.com/pablovarela/media-server-engine/internal/compose"
	"github.com/pablovarela/media-server-engine/internal/installation"
	"github.com/pablovarela/media-server-engine/internal/selfupdate"
	"github.com/pablovarela/media-server-engine/internal/version"
	mock "github.com/stretchr/testify/mock"
)

// newMockComposeRunner creates a new instance of mockComposeRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockComposeRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockComposeRunner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockComposeRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockComposeRunner is an autogenerated mock type for the composeRunner type
type mockComposeRunner struct {
	mock.Mock
}

type mockComposeRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockComposeRunner) EXPECT() *mockComposeRunner_Expecter {
	return &mockComposeRunner_Expecter{mock: &_m.Mock}
}

// Down provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Down(ctx context.Context, project *types.Project) error {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Down")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) error); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Down_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Down'
type mockComposeRunner_Down_Call struct {
	*mock.Call
}

// Down is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
func (_e *mockComposeRunner_Expecter) Down(ctx any, project any) *mockComposeRunner_Down_Call {
	return &mockComposeRunner_Down_Call{Call: _e.mock.On("Down", ctx, project)}
}

func (_c *mockComposeRunner_Down_Call) Run(run func(ctx context.Context, project *types.Project)) *mockComposeRunner_Down_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Down_Call) Return(err error) *mockComposeRunner_Down_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Down_Call) RunAndReturn(run func(ctx context.Context, project *types.Project) error) *mockComposeRunner_Down_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Load(ctx context.Context, i *installation.Installation, kind compose.Kind, variables []string, profiles []string) (*types.Project, error) {
	ret := _mock.Called(ctx, i, kind, variables, profiles)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *types.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *installation.Installation, compose.Kind, []string, []string) (*types.Project, error)); ok {
		return returnFunc(ctx, i, kind, variables, profiles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *installation.Installation, compose.Kind, []string, []string) *types.Project); ok {
		r0 = returnFunc(ctx, i, kind, variables, profiles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *installation.Installation, compose.Kind, []string, []string) error); ok {
		r1 = returnFunc(ctx, i, kind, variables, profiles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockComposeRunner_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type mockComposeRunner_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - i *installation.Installation
//   - kind compose.Kind
//   - variables []string
//   - profiles []string
func (_e *mockComposeRunner_Expecter) Load(ctx any, i any, kind any, variables any, profiles any) *mockComposeRunner_Load_Call {
	return &mockComposeRunner_Load_Call{Call: _e.mock.On("Load", ctx, i, kind, variables, profiles)}
}

func (_c *mockComposeRunner_Load_Call) Run(run func(ctx context.Context, i *installation.Installation, kind compose.Kind, variables []string, profiles []string)) *mockComposeRunner_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *installation.Installation
		if args[1] != nil {
			arg1 = args[1].(*installation.Installation)
		}
		var arg2 compose.Kind
		if args[2] != nil {
			arg2 = args[2].(compose.Kind)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Load_Call) Return(project *types.Project, err error) *mockComposeRunner_Load_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *mockComposeRunner_Load_Call) RunAndReturn(run func(ctx context.Context, i *installation.Installation, kind compose.Kind, variables []string, profiles []string) (*types.Project, error)) *mockComposeRunner_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Logs provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Logs(ctx context.Context, project *types.Project, options compose.LogsOptions, w io.Writer) error {
	ret := _mock.Called(ctx, project, options, w)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, compose.LogsOptions, io.Writer) error); ok {
		r0 = returnFunc(ctx, project, options, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type mockComposeRunner_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - options compose.LogsOptions
//   - w io.Writer
func (_e *mockComposeRunner_Expecter) Logs(ctx any, project any, options any, w any) *mockComposeRunner_Logs_Call {
	return &mockComposeRunner_Logs_Call{Call: _e.mock.On("Logs", ctx, project, options, w)}
}

func (_c *mockComposeRunner_Logs_Call) Run(run func(ctx context.Context, project *types.Project, options compose.LogsOptions, w io.Writer)) *mockComposeRunner_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 compose.LogsOptions
		if args[2] != nil {
			arg2 = args[2].(compose.LogsOptions)
		}
		var arg3 io.Writer
		if args[3] != nil {
			arg3 = args[3].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Logs_Call) Return(err error) *mockComposeRunner_Logs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Logs_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, options compose.LogsOptions, w io.Writer) error) *mockComposeRunner_Logs_Call {
	_c.Call.Return(run)
	return _c
}

// Ps provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Ps(ctx context.Context, project *types.Project) ([]compose.Container, error) {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Ps")
	}

	var r0 []compose.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) ([]compose.Container, error)); ok {
		return returnFunc(ctx, project)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) []compose.Container); ok {
		r0 = returnFunc(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compose.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Project) error); ok {
		r1 = returnFunc(ctx, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockComposeRunner_Ps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ps'
type mockComposeRunner_Ps_Call struct {
	*mock.Call
}

// Ps is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
func (_e *mockComposeRunner_Expecter) Ps(ctx any, project any) *mockComposeRunner_Ps_Call {
	return &mockComposeRunner_Ps_Call{Call: _e.mock.On("Ps", ctx, project)}
}

func (_c *mockComposeRunner_Ps_Call) Run(run func(ctx context.Context, project *types.Project)) *mockComposeRunner_Ps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Ps_Call) Return(containers []compose.Container, err error) *mockComposeRunner_Ps_Call {
	_c.Call.Return(containers, err)
	return _c
}

func (_c *mockComposeRunner_Ps_Call) RunAndReturn(run func(ctx context.Context, project *types.Project) ([]compose.Container, error)) *mockComposeRunner_Ps_Call {
	_c.Call.Return(run)
	return _c
}

// Restart provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Restart(ctx context.Context, project *types.Project, services []string) error {
	ret := _mock.Called(ctx, project, services)

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, []string) error); ok {
		r0 = returnFunc(ctx, project, services)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type mockComposeRunner_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - services []string
func (_e *mockComposeRunner_Expecter) Restart(ctx any, project any, services any) *mockComposeRunner_Restart_Call {
	return &mockComposeRunner_Restart_Call{Call: _e.mock.On("Restart", ctx, project, services)}
}

func (_c *mockComposeRunner_Restart_Call) Run(run func(ctx context.Context, project *types.Project, services []string)) *mockComposeRunner_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Restart_Call) Return(err error) *mockComposeRunner_Restart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Restart_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, services []string) error) *mockComposeRunner_Restart_Call {
	_c.Call.Return(run)
	return _c
}

// RunningServices provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) RunningServices(ctx context.Context, project *types.Project) ([]string, error) {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for RunningServices")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) ([]string, error)); ok {
		return returnFunc(ctx, project)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) []string); ok {
		r0 = returnFunc(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Project) error); ok {
		r1 = returnFunc(ctx, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockComposeRunner_RunningServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunningServices'
type mockComposeRunner_RunningServices_Call struct {
	*mock.Call
}

// RunningServices is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
func (_e *mockComposeRunner_Expecter) RunningServices(ctx any, project any) *mockComposeRunner_RunningServices_Call {
	return &mockComposeRunner_RunningServices_Call{Call: _e.mock.On("RunningServices", ctx, project)}
}

func (_c *mockComposeRunner_RunningServices_Call) Run(run func(ctx context.Context, project *types.Project)) *mockComposeRunner_RunningServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockComposeRunner_RunningServices_Call) Return(strings []string, err error) *mockComposeRunner_RunningServices_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *mockComposeRunner_RunningServices_Call) RunAndReturn(run func(ctx context.Context, project *types.Project) ([]string, error)) *mockComposeRunner_RunningServices_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Start(ctx context.Context, project *types.Project, services []string) error {
	ret := _mock.Called(ctx, project, services)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, []string) error); ok {
		r0 = returnFunc(ctx, project, services)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mockComposeRunner_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - services []string
func (_e *mockComposeRunner_Expecter) Start(ctx any, project any, services any) *mockComposeRunner_Start_Call {
	return &mockComposeRunner_Start_Call{Call: _e.mock.On("Start", ctx, project, services)}
}

func (_c *mockComposeRunner_Start_Call) Run(run func(ctx context.Context, project *types.Project, services []string)) *mockComposeRunner_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Start_Call) Return(err error) *mockComposeRunner_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Start_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, services []string) error) *mockComposeRunner_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Stop(ctx context.Context, project *types.Project) error {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project) error); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type mockComposeRunner_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
func (_e *mockComposeRunner_Expecter) Stop(ctx any, project any) *mockComposeRunner_Stop_Call {
	return &mockComposeRunner_Stop_Call{Call: _e.mock.On("Stop", ctx, project)}
}

func (_c *mockComposeRunner_Stop_Call) Run(run func(ctx context.Context, project *types.Project)) *mockComposeRunner_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Stop_Call) Return(err error) *mockComposeRunner_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Stop_Call) RunAndReturn(run func(ctx context.Context, project *types.Project) error) *mockComposeRunner_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type mockComposeRunner
func (_mock *mockComposeRunner) Up(ctx context.Context, project *types.Project, services []string, wait compose.Wait) error {
	ret := _mock.Called(ctx, project, services, wait)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Project, []string, compose.Wait) error); ok {
		r0 = returnFunc(ctx, project, services, wait)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockComposeRunner_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type mockComposeRunner_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - ctx context.Context
//   - project *types.Project
//   - services []string
//   - wait compose.Wait
func (_e *mockComposeRunner_Expecter) Up(ctx any, project any, services any, wait any) *mockComposeRunner_Up_Call {
	return &mockComposeRunner_Up_Call{Call: _e.mock.On("Up", ctx, project, services, wait)}
}

func (_c *mockComposeRunner_Up_Call) Run(run func(ctx context.Context, project *types.Project, services []string, wait compose.Wait)) *mockComposeRunner_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Project
		if args[1] != nil {
			arg1 = args[1].(*types.Project)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 compose.Wait
		if args[3] != nil {
			arg3 = args[3].(compose.Wait)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockComposeRunner_Up_Call) Return(err error) *mockComposeRunner_Up_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockComposeRunner_Up_Call) RunAndReturn(run func(ctx context.Context, project *types.Project, services []string, wait compose.Wait) error) *mockComposeRunner_Up_Call {
	_c.Call.Return(run)
	return _c
}

// newMockUpdater creates a new instance of mockUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUpdater {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockUpdater is an autogenerated mock type for the updater type
type mockUpdater struct {
	mock.Mock
}

type mockUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUpdater) EXPECT() *mockUpdater_Expecter {
	return &mockUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function for the type mockUpdater
func (_mock *mockUpdater) Update(ctx context.Context, current version.Build, force bool, progress selfupdate.Progress) (selfupdate.Result, error) {
	ret := _mock.Called(ctx, current, force, progress)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 selfupdate.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, version.Build, bool, selfupdate.Progress) (selfupdate.Result, error)); ok {
		return returnFunc(ctx, current, force, progress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, version.Build, bool, selfupdate.Progress) selfupdate.Result); ok {
		r0 = returnFunc(ctx, current, force, progress)
	} else {
		r0 = ret.Get(0).(selfupdate.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, version.Build, bool, selfupdate.Progress) error); ok {
		r1 = returnFunc(ctx, current, force, progress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - current version.Build
//   - force bool
//   - progress selfupdate.Progress
func (_e *mockUpdater_Expecter) Update(ctx any, current any, force any, progress any) *mockUpdater_Update_Call {
	return &mockUpdater_Update_Call{Call: _e.mock.On("Update", ctx, current, force, progress)}
}

func (_c *mockUpdater_Update_Call) Run(run func(ctx context.Context, current version.Build, force bool, progress selfupdate.Progress)) *mockUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 version.Build
		if args[1] != nil {
			arg1 = args[1].(version.Build)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 selfupdate.Progress
		if args[3] != nil {
			arg3 = args[3].(selfupdate.Progress)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockUpdater_Update_Call) Return(result selfupdate.Result, err error) *mockUpdater_Update_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockUpdater_Update_Call) RunAndReturn(run func(ctx context.Context, current version.Build, force bool, progress selfupdate.Progress) (selfupdate.Result, error)) *mockUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}
