// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cmd

import (
	"context"

	"github.com/pablovarela/media-server-engine/internal/selfupdate"
	"github.com/pablovarela/media-server-engine/internal/version"
	mock "github.com/stretchr/testify/mock"
)

// newMockUpdater creates a new instance of mockUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUpdater {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockUpdater is an autogenerated mock type for the updater type
type mockUpdater struct {
	mock.Mock
}

type mockUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUpdater) EXPECT() *mockUpdater_Expecter {
	return &mockUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function for the type mockUpdater
func (_mock *mockUpdater) Update(ctx context.Context, current version.Build, force bool) (selfupdate.Result, error) {
	ret := _mock.Called(ctx, current, force)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 selfupdate.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, version.Build, bool) (selfupdate.Result, error)); ok {
		return returnFunc(ctx, current, force)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, version.Build, bool) selfupdate.Result); ok {
		r0 = returnFunc(ctx, current, force)
	} else {
		r0 = ret.Get(0).(selfupdate.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, version.Build, bool) error); ok {
		r1 = returnFunc(ctx, current, force)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - current version.Build
//   - force bool
func (_e *mockUpdater_Expecter) Update(ctx any, current any, force any) *mockUpdater_Update_Call {
	return &mockUpdater_Update_Call{Call: _e.mock.On("Update", ctx, current, force)}
}

func (_c *mockUpdater_Update_Call) Run(run func(ctx context.Context, current version.Build, force bool)) *mockUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 version.Build
		if args[1] != nil {
			arg1 = args[1].(version.Build)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockUpdater_Update_Call) Return(result selfupdate.Result, err error) *mockUpdater_Update_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockUpdater_Update_Call) RunAndReturn(run func(ctx context.Context, current version.Build, force bool) (selfupdate.Result, error)) *mockUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}
