// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package selfupdate

import (
	"context"
	"io"

	"github.com/pablovarela/media-server-engine/internal/github"
	mock "github.com/stretchr/testify/mock"
)

// newMockReleaseSource creates a new instance of mockReleaseSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockReleaseSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockReleaseSource {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockReleaseSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockReleaseSource is an autogenerated mock type for the releaseSource type
type mockReleaseSource struct {
	mock.Mock
}

type mockReleaseSource_Expecter struct {
	mock *mock.Mock
}

func (_m *mockReleaseSource) EXPECT() *mockReleaseSource_Expecter {
	return &mockReleaseSource_Expecter{mock: &_m.Mock}
}

// Download provides a mock function for the type mockReleaseSource
func (_mock *mockReleaseSource) Download(ctx context.Context, asset github.Asset, w io.Writer) error {
	ret := _mock.Called(ctx, asset, w)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, github.Asset, io.Writer) error); ok {
		r0 = returnFunc(ctx, asset, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockReleaseSource_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type mockReleaseSource_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - asset github.Asset
//   - w io.Writer
func (_e *mockReleaseSource_Expecter) Download(ctx any, asset any, w any) *mockReleaseSource_Download_Call {
	return &mockReleaseSource_Download_Call{Call: _e.mock.On("Download", ctx, asset, w)}
}

func (_c *mockReleaseSource_Download_Call) Run(run func(ctx context.Context, asset github.Asset, w io.Writer)) *mockReleaseSource_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 github.Asset
		if args[1] != nil {
			arg1 = args[1].(github.Asset)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockReleaseSource_Download_Call) Return(err error) *mockReleaseSource_Download_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockReleaseSource_Download_Call) RunAndReturn(run func(ctx context.Context, asset github.Asset, w io.Writer) error) *mockReleaseSource_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Releases provides a mock function for the type mockReleaseSource
func (_mock *mockReleaseSource) Releases(ctx context.Context) ([]github.Release, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Releases")
	}

	var r0 []github.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]github.Release, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []github.Release); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]github.Release)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockReleaseSource_Releases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Releases'
type mockReleaseSource_Releases_Call struct {
	*mock.Call
}

// Releases is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockReleaseSource_Expecter) Releases(ctx any) *mockReleaseSource_Releases_Call {
	return &mockReleaseSource_Releases_Call{Call: _e.mock.On("Releases", ctx)}
}

func (_c *mockReleaseSource_Releases_Call) Run(run func(ctx context.Context)) *mockReleaseSource_Releases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockReleaseSource_Releases_Call) Return(releases []github.Release, err error) *mockReleaseSource_Releases_Call {
	_c.Call.Return(releases, err)
	return _c
}

func (_c *mockReleaseSource_Releases_Call) RunAndReturn(run func(ctx context.Context) ([]github.Release, error)) *mockReleaseSource_Releases_Call {
	_c.Call.Return(run)
	return _c
}

// newMockVersionReader creates a new instance of mockVersionReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockVersionReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockVersionReader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockVersionReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockVersionReader is an autogenerated mock type for the versionReader type
type mockVersionReader struct {
	mock.Mock
}

type mockVersionReader_Expecter struct {
	mock *mock.Mock
}

func (_m *mockVersionReader) EXPECT() *mockVersionReader_Expecter {
	return &mockVersionReader_Expecter{mock: &_m.Mock}
}

// Version provides a mock function for the type mockVersionReader
func (_mock *mockVersionReader) Version(ctx context.Context, path string) (string, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockVersionReader_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type mockVersionReader_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *mockVersionReader_Expecter) Version(ctx any, path any) *mockVersionReader_Version_Call {
	return &mockVersionReader_Version_Call{Call: _e.mock.On("Version", ctx, path)}
}

func (_c *mockVersionReader_Version_Call) Run(run func(ctx context.Context, path string)) *mockVersionReader_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockVersionReader_Version_Call) Return(s string, err error) *mockVersionReader_Version_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockVersionReader_Version_Call) RunAndReturn(run func(ctx context.Context, path string) (string, error)) *mockVersionReader_Version_Call {
	_c.Call.Return(run)
	return _c
}

// newMockProgress creates a new instance of mockProgress. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockProgress(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockProgress {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockProgress{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockProgress is an autogenerated mock type for the Progress type
type mockProgress struct {
	mock.Mock
}

type mockProgress_Expecter struct {
	mock *mock.Mock
}

func (_m *mockProgress) EXPECT() *mockProgress_Expecter {
	return &mockProgress_Expecter{mock: &_m.Mock}
}

// Checking provides a mock function for the type mockProgress
func (_mock *mockProgress) Checking(current string, force bool) {
	_mock.Called(current, force)
	return
}

// mockProgress_Checking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checking'
type mockProgress_Checking_Call struct {
	*mock.Call
}

// Checking is a helper method to define mock.On call
//   - current string
//   - force bool
func (_e *mockProgress_Expecter) Checking(current any, force any) *mockProgress_Checking_Call {
	return &mockProgress_Checking_Call{Call: _e.mock.On("Checking", current, force)}
}

func (_c *mockProgress_Checking_Call) Run(run func(current string, force bool)) *mockProgress_Checking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockProgress_Checking_Call) Return() *mockProgress_Checking_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockProgress_Checking_Call) RunAndReturn(run func(current string, force bool)) *mockProgress_Checking_Call {
	_c.Run(run)
	return _c
}

// Updating provides a mock function for the type mockProgress
func (_mock *mockProgress) Updating(target string) {
	_mock.Called(target)
	return
}

// mockProgress_Updating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Updating'
type mockProgress_Updating_Call struct {
	*mock.Call
}

// Updating is a helper method to define mock.On call
//   - target string
func (_e *mockProgress_Expecter) Updating(target any) *mockProgress_Updating_Call {
	return &mockProgress_Updating_Call{Call: _e.mock.On("Updating", target)}
}

func (_c *mockProgress_Updating_Call) Run(run func(target string)) *mockProgress_Updating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockProgress_Updating_Call) Return() *mockProgress_Updating_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockProgress_Updating_Call) RunAndReturn(run func(target string)) *mockProgress_Updating_Call {
	_c.Run(run)
	return _c
}
